import React from 'react';
import { 
  Utensils, ShoppingCart, Scissors, Heart, PawPrint, Home, Wrench, 
  Dumbbell, CarFront, BookOpen, Monitor, Shirt, Ticket, Map as MapIcon, 
  Store as StoreIcon,
  LayoutGrid, Pill, Briefcase, Plane, Zap,
  Beef, Coffee, Pizza, Croissant, Soup, Cake, Sandwich, 
  Stethoscope, Package, Clock, Target, Settings, Dog,
  Star, Tag, Award, TrendingUp, ChevronRight, MessageSquare, Users,
  Apple, Building2, Leaf, Shield, PaintRoller, Hammer, Droplets, Laptop,
  Baby, GraduationCap, Microscope, Brain, Sparkles, Smile, Beer, 
  Activity, Eye, FileText, Globe, Calendar, Music, PartyPopper, Globe2, Edit3, User, Bell, Search,
  Camera, Vote, Handshake, Flame, Milestone, History, Home as HomeIcon,
  MessageCircle, HelpCircle, UserCheck, Recycle, Scale, Calculator, PenTool, Ruler,
  Key, Fan, Truck, Shovel,
  Meh, ThumbsDown, Gift, RefreshCw,
  Landmark, Tent, TicketPercent, Percent, Newspaper,
  Palette, Printer, Book, Lightbulb, Bike, Sofa, Smartphone, Headphones,
  Wifi, MapPin, Trash2, ShieldAlert, Megaphone, ShieldCheck,
  Circle, Flower, Swords, Gamepad, Gamepad2, Church, Film, Mic, Bus,
  Lock, Wind, Disc, Cpu,
  // Added icons for specific health needs
  Stethoscope as StethoscopeIcon,
  Brain as BrainIcon,
  Activity as ActivityIcon
} from 'lucide-react';
import { AdType, Category, Store, Story, EditorialCollection, Job, CommunityPost, NeighborhoodCommunity, Classified, RealEstateProperty } from '@/types';
import { getStoreLogo } from '@/utils/mockLogos';


export const CATEGORIES: Category[] = [
  { id: 'cat-servicos', name: 'Serviços', slug: 'servicos', icon: <Wrench />, color: 'bg-brand-blue' },
  { id: 'cat-alimentacao', name: 'Alimentação', slug: 'alimentacao', icon: <Soup />, color: 'bg-brand-blue' },
  { id: 'cat-restaurantes', name: 'Restaurantes', slug: 'restaurantes', icon: <Utensils />, color: 'bg-brand-blue' },
  { id: 'cat-mercados', name: 'Mercados', slug: 'mercados', icon: <ShoppingCart />, color: 'bg-brand-blue' },
  { id: 'cat-farmacias', name: 'Farmácias', slug: 'farmacias', icon: <Pill />, color: 'bg-brand-blue' },
  { id: 'cat-autos', name: 'Autos', slug: 'autos', icon: <CarFront />, color: 'bg-brand-blue' },
  { id: 'cat-moda', name: 'Moda', slug: 'moda', icon: <Shirt />, color: 'bg-brand-blue' },
  { id: 'cat-beleza', name: 'Beleza', slug: 'beleza', icon: <Scissors />, color: 'bg-brand-blue' },
  { id: 'cat-casa', name: 'Casa', slug: 'casa', icon: <HomeIcon />, color: 'bg-brand-blue' },
  { id: 'cat-informatica', name: 'Informática', slug: 'informatica', icon: <Monitor />, color: 'bg-brand-blue' },
  { id: 'cat-papelaria', name: 'Papelaria', slug: 'papelaria', icon: <PenTool />, color: 'bg-brand-blue' },
  { id: 'cat-pets', name: 'Pets', slug: 'pets', icon: <PawPrint />, color: 'bg-brand-blue' },
  { id: 'cat-saude', name: 'Saúde', slug: 'saude', icon: <Heart />, color: 'bg-brand-blue' },
  { id: 'cat-educacao', name: 'Educação', slug: 'educacao', icon: <BookOpen />, color: 'bg-brand-blue' },
  { id: 'cat-esporte', name: 'Esporte', slug: 'esporte', icon: <Dumbbell />, color: 'bg-brand-blue' },
  { id: 'cat-bemestar', name: 'Bem-estar', slug: 'bemestar', icon: <Smile />, color: 'bg-brand-blue' },
  { id: 'cat-infantil', name: 'Infantil', slug: 'infantil', icon: <Baby />, color: 'bg-brand-blue' },
  { id: 'cat-servicospublicos', name: 'Serviços Públicos', slug: 'servicospublicos', icon: <Landmark />, color: 'bg-brand-blue' },
  { id: 'cat-eventos', name: 'Eventos', slug: 'eventos', icon: <PartyPopper />, color: 'bg-brand-blue' },
  { id: 'cat-condominios', name: 'Condomínios', slug: 'condominios', icon: <Building2 />, color: 'bg-brand-blue' },
  { id: 'cat-lazer', name: 'Lazer', slug: 'lazer', icon: <Tent />, color: 'bg-brand-blue' },
  { id: 'cat-cupons', name: 'Cupons', slug: 'cupons', icon: <TicketPercent />, color: 'bg-brand-blue' },
  { id: 'cat-promocoes', name: 'Promoções', slug: 'promocoes', icon: <Percent />, color: 'bg-brand-blue' },
  { id: 'cat-classificados', name: 'Classificados', slug: 'classificados', icon: <Newspaper />, color: 'bg-brand-blue' },
  { id: 'cat-achados', name: 'Achados e Perdidos', slug: 'achados', icon: <Search />, color: 'bg-brand-blue' },
];

export const SUBCATEGORIES: Record<string, { name: string; icon: React.ReactNode }[]> = {
  'Serviços': [
    { name: 'Elétrica', icon: <Zap /> },
    { name: 'Hidráulica', icon: <Droplets /> },
    { name: 'Chaveiro', icon: <Key /> },
    { name: 'Marido de Aluguel', icon: <Hammer /> },
    { name: 'Pintura', icon: <PaintRoller /> },
    { name: 'Limpeza', icon: <Sparkles /> },
    { name: 'Jardinagem', icon: <Leaf /> },
    { name: 'Montagem de Móveis', icon: <Settings /> },
  ],
  'Alimentação': [
    { name: 'Marmitas', icon: <Package /> },
    { name: 'Lanches', icon: <Sandwich /> },
    { name: 'Doces', icon: <Cake /> },
    { name: 'Salgados', icon: <Croissant /> },
    { name: 'Comida Caseira', icon: <Soup /> },
    { name: 'Bebidas', icon: <Beer /> },
    { name: 'Produtos Naturais', icon: <Apple /> },
    { name: 'Congelados', icon: <Package /> },
  ],
  'Restaurantes': [
    { name: 'Pizzarias', icon: <Pizza /> },
    { name: 'Hamburguerias', icon: <Beef /> },
    { name: 'Brasileira', icon: <Utensils /> },
    { name: 'Japonesa', icon: <Globe2 /> },
    { name: 'Italiana', icon: <Pizza /> },
    { name: 'Árabe', icon: <Globe /> },
    { name: 'Self-service', icon: <Utensils /> },
    { name: 'Delivery', icon: <Bike /> },
  ],
  'Mercados': [
    { name: 'Supermercados', icon: <ShoppingCart /> },
    { name: 'Mercadinhos', icon: <StoreIcon /> },
    { name: 'Hortifruti', icon: <Apple /> },
    { name: 'Açougue', icon: <Beef /> },
    { name: 'Peixaria', icon: <Globe /> },
    { name: 'Conveniência', icon: <Clock /> },
    { name: 'Bebidas', icon: <Beer /> },
    { name: 'Importados', icon: <Globe2 /> },
  ],
  'Farmácias': [
    { name: 'Farmácias', icon: <Pill /> },
    { name: 'Manipulados', icon: <Microscope /> },
    { name: 'Materiais Médicos', icon: <Stethoscope /> },
  ],
  'Autos': [
    { name: 'Carro', icon: <CarFront /> },
    { name: 'Moto', icon: <Bike /> },
    { name: 'Oficinas', icon: <Wrench /> },
    { name: 'Elétrica', icon: <Zap /> },
    { name: 'Lava Jato', icon: <Droplets /> },
    { name: 'Borracharia', icon: <Circle /> },
    { name: 'Guincho', icon: <Truck /> },
    { name: 'Peças', icon: <Settings /> },
    { name: 'Estética', icon: <Sparkles /> },
    { name: 'Acessórios', icon: <Star /> },
    { name: 'Oficina mecânica', icon: <Wrench /> },
    { name: 'Auto elétrica', icon: <Zap /> },
    { name: 'Funilaria e pintura', icon: <PaintRoller /> },
    { name: 'Alinhamento e balanceamento', icon: <Scale /> },
    { name: 'Troca de óleo', icon: <Droplets /> },
    { name: 'Suspensão e freios', icon: <Disc /> },
    { name: 'Ar-condicionado automotivo', icon: <Wind /> },
    { name: 'Guincho e reboque', icon: <Truck /> },
    { name: 'Oficina de motos', icon: <Wrench /> },
    { name: 'Elétrica de motos', icon: <Zap /> },
    { name: 'Mecânica geral', icon: <Settings /> },
    { name: 'Injeção eletrônica', icon: <Cpu /> },
    { name: 'Peças e acessórios', icon: <Package /> },
    { name: 'Guincho para motos', icon: <Truck /> },
  ],
  'Moda': [
    { name: 'Feminina', icon: <Shirt /> },
    { name: 'Masculina', icon: <User /> },
    { name: 'Infantil', icon: <Baby /> },
    { name: 'Camisas', icon: <Shirt /> },
    { name: 'Calças', icon: <LayoutGrid /> },
    { name: 'Vestidos', icon: <Star /> },
    { name: 'Shorts', icon: <LayoutGrid /> },
    { name: 'Jeans', icon: <LayoutGrid /> },
    { name: 'Moda Íntima', icon: <Heart /> },
    { name: 'Moda Fitness', icon: <Dumbbell /> },
    { name: 'Moda Plus Size', icon: <User /> },
    { name: 'Calçados', icon: <Package /> },
    { name: 'Acessórios', icon: <Star /> },
  ],
  'Beleza': [
    { name: 'Salão de Cabelo', icon: <Scissors /> },
    { name: 'Manicure', icon: <Handshake /> },
    { name: 'Estética Facial', icon: <Sparkles /> },
    { name: 'Estética Corporal', icon: <User /> },
    { name: 'Barbearia', icon: <Scissors /> },
    { name: 'Maquiagem', icon: <Palette /> },
    { name: 'Depilação', icon: <Sparkles /> },
    { name: 'Massagem', icon: <Heart /> },
  ],
  'Casa': [
    { name: 'Móveis', icon: <Sofa /> },
    { name: 'Decoração', icon: <Palette /> },
    { name: 'Iluminação', icon: <Lightbulb /> },
    { name: 'Utensílios', icon: <Utensils /> },
    { name: 'Cama Mesa Banho', icon: <LayoutGrid /> },
    { name: 'Jardinagem', icon: <Flower /> },
    { name: 'Construção', icon: <Hammer /> },
    { name: 'Eletrodomésticos', icon: <Zap /> },
  ],
  'Informática': [
    { name: 'Assistência Técnica', icon: <Wrench /> },
    { name: 'Computadores', icon: <Monitor /> },
    { name: 'Celulares', icon: <Smartphone /> },
    { name: 'Acessórios', icon: <Headphones /> },
    { name: 'Redes', icon: <Wifi /> },
    { name: 'Impressoras', icon: <Printer /> },
    { name: 'Formatação', icon: <Settings /> },
    { name: 'Suporte Técnico', icon: <HelpCircle /> },
  ],
  'Papelaria': [
    { name: 'Escolar', icon: <Book /> },
    { name: 'Escritório', icon: <Briefcase /> },
    { name: 'Impressões', icon: <Printer /> },
    { name: 'Encadernação', icon: <BookOpen /> },
    { name: 'Brindes', icon: <Gift /> },
    { name: 'Festas', icon: <PartyPopper /> },
    { name: 'Arte', icon: <Palette /> },
    { name: 'Livros', icon: <BookOpen /> },
  ],
  'Pets': [
    { name: 'Pet Shop', icon: <ShoppingCart /> },
    { name: 'Banho e Tosa', icon: <Scissors /> },
    { name: 'Veterinário', icon: <Stethoscope /> },
    { name: 'Adestramento', icon: <Award /> },
    { name: 'Hospedagem', icon: <HomeIcon /> },
    { name: 'Passeador de Pets', icon: <User /> },
    { name: 'Cuidador de Pets', icon: <Heart /> },
    { name: 'Pets Perdidos', icon: <Search /> },
  ],
  'Saúde': [
    { name: 'Ginecologia', icon: <User /> },
    { name: 'Obstetrícia', icon: <Baby /> },
    { name: 'Mastologia', icon: <Heart /> },
    { name: 'Urologia', icon: <User /> },
    { name: 'Proctologia', icon: <ActivityIcon /> },
    { name: 'Pediatria', icon: <Baby /> },
    { name: 'Psicologia infantil', icon: <BrainIcon /> },
    { name: 'Nutrição infantil', icon: <Apple /> },
    { name: 'Geriatria', icon: <Users /> },
    { name: 'Fisioterapia motora', icon: <ActivityIcon /> },
    { name: 'Dentistas', icon: <Smile /> },
    { name: 'Cardiologia', icon: <Heart /> },
    { name: 'Exames e Diagnósticos', icon: <Microscope /> },
    { name: 'Psicologia', icon: <BrainIcon /> },
    { name: 'Clínicas', icon: <Building2 /> },
    { name: 'Terapias Alternativas', icon: <Sparkles /> },
  ],
  'Educação': [
    { name: 'Escolas', icon: <Building2 /> },
    { name: 'Cursos Livres', icon: <GraduationCap /> },
    { name: 'Idiomas', icon: <Globe /> },
    { name: 'Reforço Escolar', icon: <Edit3 /> },
    { name: 'Aulas Particulares', icon: <User /> },
    { name: 'Profissionalizantes', icon: <Briefcase /> },
    { name: 'Informática', icon: <Monitor /> },
    { name: 'Preparatórios', icon: <BookOpen /> },
  ],
  'Esporte': [
    { name: 'Academias', icon: <Dumbbell /> },
    { name: 'Personal Trainer', icon: <User /> },
    { name: 'Artes Marciais', icon: <Swords /> },
    { name: 'Dança', icon: <Music /> },
    { name: 'Futebol', icon: <Target /> },
    { name: 'Pilates', icon: <Activity /> },
    { name: 'Yoga', icon: <Smile /> },
    { name: 'Funcional', icon: <Zap /> },
  ],
  'Bem-estar': [
    { name: 'Massoterapia', icon: <Heart /> },
    { name: 'Terapias Holísticas', icon: <Sparkles /> },
    { name: 'Meditação', icon: <Smile /> },
    { name: 'Yoga', icon: <Activity /> },
    { name: 'Acupuntura', icon: <MapPin /> },
    { name: 'Reiki', icon: <Handshake /> },
    { name: 'Quiropraxia', icon: <User /> },
    { name: 'Saúde Mental', icon: <Brain /> },
  ],
  'Infantil': [
    { name: 'Escolas Infantis', icon: <Building2 /> },
    { name: 'Berçários', icon: <Baby /> },
    { name: 'Brinquedos', icon: <Gamepad /> },
    { name: 'Roupas Infantis', icon: <Shirt /> },
    { name: 'Festas Infantis', icon: <PartyPopper /> },
    { name: 'Cursos Infantis', icon: <BookOpen /> },
    { name: 'Atividades', icon: <Star /> },
    { name: 'Cuidados', icon: <Heart /> },
  ],
  'Serviços Públicos': [
    { name: 'Postos de Saúde', icon: <Heart /> },
    { name: 'Escolas Públicas', icon: <Building2 /> },
    { name: 'Delegacias', icon: <Shield /> },
    { name: 'Assistência Social', icon: <Users /> },
    { name: 'Transporte Público', icon: <Bus /> },
    { name: 'Coleta de Lixo', icon: <Trash2 /> },
    { name: 'Defesa Civil', icon: <ShieldAlert /> },
    { name: 'Órgãos Municipais', icon: <Landmark /> },
  ],
  'Eventos': [
    { name: 'Culturais', icon: <Music /> },
    { name: 'Esportivos', icon: <Dumbbell /> },
    { name: 'Feiras', icon: <StoreIcon /> },
    { name: 'Shows', icon: <Mic /> },
    { name: 'Religiosos', icon: <Church /> },
    { name: 'Gastronômicos', icon: <Utensils /> },
    { name: 'Comunitários', icon: <Users /> },
    { name: 'Infantis', icon: <Baby /> },
  ],
  'Condomínios': [
    { name: 'Avisos', icon: <Bell /> },
    { name: 'Comunicados', icon: <Megaphone /> },
    { name: 'Eventos Internos', icon: <Calendar /> },
    { name: 'Prestadores', icon: <Wrench /> },
    { name: 'Segurança', icon: <ShieldCheck /> },
    { name: 'Administração', icon: <Briefcase /> },
    { name: 'Achados e Perdidos', icon: <Search /> },
    { name: 'Vida em Condomínio', icon: <Users /> },
  ],
  'Lazer': [
    { name: 'Bares', icon: <Beer /> },
    { name: 'Cafés', icon: <Coffee /> },
    { name: 'Cinemas', icon: <Film /> },
    { name: 'Parques', icon: <Tent /> },
    { name: 'Convivência', icon: <Users /> },
    { name: 'Jogos', icon: <Gamepad2 /> },
    { name: 'Turismo Local', icon: <Globe2 /> },
    { name: 'Passeios', icon: <MapIcon /> },
  ],
  'Cupons': [
    { name: 'Alimentação', icon: <Utensils /> },
    { name: 'Serviços', icon: <Wrench /> },
    { name: 'Beleza', icon: <Scissors /> },
    { name: 'Moda', icon: <Shirt /> },
    { name: 'Saúde', icon: <Heart /> },
    { name: 'Pets', icon: <PawPrint /> },
    { name: 'Lazer', icon: <Ticket /> },
    { name: 'Educação', icon: <BookOpen /> },
  ],
  'Promoções': [
    { name: 'Semanais', icon: <Calendar /> },
    { name: 'Relâmpago', icon: <Zap /> },
    { name: 'Datas Comemorativas', icon: <Gift /> },
    { name: 'Novas Lojas', icon: <StoreIcon /> },
    { name: 'Queima de Estoque', icon: <Flame /> },
    { name: 'Descontos Especiais', icon: <Tag /> },
    { name: 'Exclusivas', icon: <Lock /> },
    { name: 'Bairro', icon: <MapPin /> },
  ],
  'Classificados': [
    { name: 'Vendo', icon: <Tag /> },
    { name: 'Compro', icon: <Search /> },
    { name: 'Alugo', icon: <Key /> },
    { name: 'Troco', icon: <RefreshCw /> },
    { name: 'Empregos', icon: <Briefcase /> },
    { name: 'Serviços Autônomos', icon: <User /> },
    { name: 'Imóveis', icon: <Building2 /> },
    { name: 'Outros', icon: <HelpCircle /> },
  ],
  'Achados e Perdidos': [
    { name: 'Pets Perdidos', icon: <PawPrint /> },
    { name: 'Pets Encontrados', icon: <PawPrint /> },
    { name: 'Documentos', icon: <FileText /> },
    { name: 'Chaves', icon: <Key /> },
    { name: 'Objetos', icon: <Package /> },
    { name: 'Bicicletas', icon: <Bike /> },
    { name: 'Eletrônicos', icon: <Smartphone /> },
    { name: 'Outros', icon: <Search /> },
  ]
};

export const ALL_TAGS = [
  'tênis', 'camisa', 'camiseta', 'calça', 'bermuda', 'vestido', 'saia', 'moletom', 'jaqueta', 'roupa social', 'roupa feminina', 'roupa masculina',
  'relógio', 'óculos', 'bolsa', 'mochila', 'cinto', 'pulseira', 'colar', 'boné',
  'ração', 'banho e tosa', 'brinquedo pet', 'coleira', 'petiscos', 'veterinário', 'adestramento', 'transporte pet',
  'corte de cabelo', 'manicure', 'pedicure', 'maquiagem', 'estética facial', 'sobrancelha', 'depilação', 'hidratação capilar',
  'troca de óleo', 'alinhamento', 'balanceamento', 'revisão automotiva', 'lava jato', 'auto elétrica', 'funilaria', 'vistoria veicular',
  'clínica médica', 'dentista', 'psicologia', 'fisioterapia', 'exames laboratoriais', 'nutrição', 'terapias alternativas', 'saúde preventiva',
  'eletricista', 'encanador', 'pedreiro', 'pintor', 'chaveiro', 'montagem de móveis', 'limpeza residencial', 'manutenção geral'
];

const IMG_IDS: Record<string, string[]> = {
  'Alimentação': ['1504674900247-0877df9cc836', '1555939594-58d7cb561ad1', '1565299624946-b28f40a0ae38', '1567620905732-2d1ec7ab7445', '1467003909585-63c6385cdb26', '1540189549336-e6e99c3679fe', '1568901346375-23c9450c58cd', '1484723091739-30a097e8f929'],
  'Pets': ['1516734212186-a967f81ad0d7', '1543466835-00a7907e9de1', '1537151608828-ea2b11777ee8', '1514888286974-6c27e9cce25b', '1583511655857-d19b40a7a54e', '1583337130417-3346a1be7dee'],
  'Profissionais': ['1556761175-5973dc0f32e7', '1542744173-8e7e53415bb0', '1507679799938-d738f46fbcfc', '1521791136064-7986c292027b'],
  'Saúde': ['1579684385127-1ef15d508118', '1584515933487-9d317552d894', '1576091160399-112ba8d25d1d', '1551076805-e2983fe3600c'],
  'Serviços': ['1581578731117-10d52b4d8051', '1621905251189-08b45d6a269e', '1504328345606-18aff0858706', '1584622024886-0a02091d3744'],
  'Beleza': ['1560066984-118c38b64a75', '1522337660859-02fbefca4702', '1562322140-8baeececf3df', '1616394584738-fc6e612e71b9'],
  'Autos': ['1486262715619-67b85e0b08d3', '1492144534655-ae79c964c9d7', '1562920618-971c26b268b6', '1503376763036-066120622c74'],
  'Mercados': ['1542838132-92c53300491e', '1578916171728-566855ce2dce', '1583258292688-d0213dc5a3a8', '1534723452202-428aae1ad99d'],
  'Casa': ['1556228453-efd6c1ff04f6', '1583847268964-b8bc40f9e2b8', '1513694203232-719a280e022f', '1493809842364-78817add7ffb'],
  'Esportes': ['1534438327276-14e5300c3a48', '1517836357463-c25dfe9495ac', '1574680096141-1c5700243a36', '1571902943202-507ec2618e8f'],
  'Lazer': ['1514525253361-bee23e63d890', '1470225620780-dba8ba36b745', '1533174072545-a8cd56c24385', '1564057865243-d343468b8d0e'],
  'Educação': ['1503676260728-1c00da094a0b', '1524178232363-1fb2b075b655', '1497633762265-9d179a990aa6', '1523240795612-9a054b0db644'],
  'Farmácia': ['1585435557343-3b092031a831', '1631549733277-628f3281783f', '1576602976047-1743ef509a18', '1587854692152-cbe660dbbb88'],
  'Moda': ['1445205170230-053b83016050', '1512436991641-6745cdb1723f', '1483985988355-763728e1935b', '1515886657613-9f3515b0c78f'],
  'Eventos': ['1511632765486-a01980e01a18', '1492684223066-81342ee5ff30', '1533174072545-a8cd56c24385', '1514525253361-bee23e63d890'],
  'Condomínios': ['1560518883-ce