import React from 'react';
import { 
  Utensils, ShoppingCart, Scissors, Heart, PawPrint, Home, Wrench, 
  Dumbbell, CarFront, BookOpen, Monitor, Shirt, Ticket, Map as MapIcon, 
  Store as StoreIcon,
  LayoutGrid, Pill, Briefcase, Plane, Zap,
  Beef, Coffee, Pizza, Croissant, Soup, Cake, Sandwich, 
  Stethoscope, Package, Clock, Target, Settings, Dog,
  Star, Tag, Award, TrendingUp, ChevronRight, MessageSquare, Users,
  Apple, Building2, Leaf, Shield, PaintRoller, Hammer, Droplets, Laptop,
  Baby, GraduationCap, Microscope, Brain, Sparkles, Smile, Beer, 
  Activity, Eye, FileText, Globe, Calendar, Music, PartyPopper, Globe2, Edit3, User, Bell, Search,
  Camera, Vote, Handshake, Flame, Milestone, History, Home as HomeIcon,
  MessageCircle, HelpCircle, UserCheck, Recycle,
  Navigation
} from 'lucide-react';
import { AdType, Category, Store, Story, EditorialCollection, Job, CommunityPost, NeighborhoodCommunity } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'cat-comida', name: 'Comida', slug: 'comida', icon: <Utensils />, color: 'bg-brand-blue' },
  { id: 'cat-pets', name: 'Pets', slug: 'pets', icon: <PawPrint />, color: 'bg-brand-blue' },
  { id: 'cat-pro', name: 'Pro', slug: 'pro', icon: <Briefcase />, color: 'bg-brand-blue' },
  { id: 'cat-saude', name: 'Saúde', slug: 'saude', icon: <Heart />, color: 'bg-brand-blue' },
  { id: 'cat-services', name: 'Serviços', slug: 'servicos', icon: <Wrench />, color: 'bg-brand-blue' },
  { id: 'cat-beauty', name: 'Beleza', slug: 'beleza', icon: <Scissors />, color: 'bg-brand-blue' },
  { id: 'cat-autos', name: 'Autos', slug: 'autos', icon: <CarFront />, color: 'bg-brand-blue' },
  { id: 'cat-mercado', name: 'Mercado', slug: 'mercado', icon: <ShoppingCart />, color: 'bg-brand-blue' },
  { id: 'cat-casa', name: 'Casa', slug: 'casa', icon: <HomeIcon />, color: 'bg-brand-blue' },
  { id: 'cat-sports', name: 'Esportes', slug: 'esportes', icon: <Dumbbell />, color: 'bg-brand-blue' },
  { id: 'cat-leisure', name: 'Lazer', slug: 'lazer', icon: <Ticket />, color: 'bg-brand-blue' },
  { id: 'cat-edu', name: 'Educação', slug: 'educacao', icon: <BookOpen />, color: 'bg-brand-blue' },
  { id: 'cat-pharmacy', name: 'Farmácia', slug: 'farmacia', icon: <Pill />, color: 'bg-brand-blue' },
  { id: 'cat-fashion', name: 'Moda', slug: 'moda', icon: <Shirt />, color: 'bg-brand-blue' },
  { id: 'cat-eventos', name: 'Eventos', slug: 'eventos', icon: <PartyPopper />, color: 'bg-brand-blue' },
  { id: 'cat-condominio', name: 'Condomínio', slug: 'condominio', icon: <Building2 />, color: 'bg-brand-blue' },
];

export const SUBCATEGORIES: Record<string, { name: string; icon: React.ReactNode }[]> = {
  'Comida': [
    { name: 'Restaurantes', icon: <Utensils /> },
    { name: 'Lanches & Hamburguerias', icon: <Beef /> },
    { name: 'Pizzarias', icon: <Pizza /> },
    { name: 'Cafés & Cafeterias', icon: <Coffee /> },
    { name: 'Delivery', icon: <Package /> },
    { name: 'Doces & Sobremesas', icon: <Cake /> },
    { name: 'Comida Caseira', icon: <Utensils /> },
    { name: 'Hortifruti & Naturais', icon: <Apple /> },
  ],
  // ... (outras subcategorias mantidas)
};

export const STORES: Store[] = [
  {
    id: 'grupo-esquematiza',
    name: 'Grupo Esquematiza',
    category: 'Serviços',
    subcategory: 'Segurança e Facilities',
    description: 'Líder em segurança, limpeza e facilities para condomínios e empresas em toda Jacarepaguá. Atendimento personalizado com foco em tecnologia e profissionais altamente treinados para garantir o bem-estar do seu patrimônio.',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3dab?q=80&w=200&auto=format&fit=crop',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop',
    rating: 5.0,
    reviewsCount: 150,
    distance: 'Freguesia • RJ',
    neighborhood: 'Freguesia',
    adType: AdType.PREMIUM,
    rua: 'Rua Cândido de Figueiredo',
    numero: '204',
    bairro: 'Tanque',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21985559480',
    telefone_fixo_publico: '2133445566',
    instagram: '@grupoesquematiza',
    business_hours: {
      segunda: { open: true, start: '08:00', end: '18:00' },
      terca: { open: true, start: '08:00', end: '18:00' },
      quarta: { open: true, start: '08:00', end: '18:00' },
      quinta: { open: true, start: '08:00', end: '18:00' },
      sexta: { open: true, start: '08:00', end: '18:00' },
      sabado: { open: false, start: '09:00', end: '14:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Faturamento (B2B)', 'Cartão de Crédito'],
    recentComments: [
      'Serviço de portaria excelente, muito educados.',
      'A limpeza do condomínio melhorou 100% com eles.',
      'Equipe muito profissional e atenciosa.'
    ],
    verified: true,
    isOpenNow: true,
    isSponsored: true
  },
  { 
    id: 'f-1', 
    name: 'Bibi Lanches', 
    category: 'Comida', 
    subcategory: 'Lanches & Hamburguerias', 
    rating: 4.8, 
    reviewsCount: 1240,
    distance: 'Freguesia', 
    adType: AdType.PREMIUM, 
    description: 'O tradicional lanche do Rio agora com o melhor atendimento da Freguesia. Sucos naturais fresquinhos, sanduíches icônicos e os melhores petiscos para o seu pós-praia ou final de dia no bairro.',
    rua: 'Estrada de Jacarepaguá',
    numero: '7500',
    bairro: 'Freguesia',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21998877665',
    telefone_fixo_publico: '2124251234',
    instagram: '@bibilanches_oficial',
    business_hours: {
      segunda: { open: true, start: '11:00', end: '00:00' },
      terca: { open: true, start: '11:00', end: '00:00' },
      quarta: { open: true, start: '11:00', end: '00:00' },
      quinta: { open: true, start: '11:00', end: '00:00' },
      sexta: { open: true, start: '11:00', end: '01:00' },
      sabado: { open: true, start: '11:00', end: '01:00' },
      domingo: { open: true, start: '11:00', end: '23:30' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro', 'Vale Refeição'],
    recentComments: [
      'Melhor suco de manga da região!',
      'O hambúrguer clássico nunca decepciona.',
      'Ambiente agradável para ir com a família.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?q=80&w=400&auto=format&fit=crop',
    verified: true,
    isOpenNow: true
  },
  { 
    id: 'f-2', 
    name: 'Studio Hair Vip', 
    category: 'Beleza', 
    subcategory: 'Salão de Cabelo', 
    rating: 4.9, 
    reviewsCount: 850,
    distance: 'Taquara', 
    adType: AdType.PREMIUM, 
    description: 'Especialistas em coloração, mechas e cortes modernos. No Studio Hair Vip, cuidamos da sua autoestima com os melhores produtos do mercado mundial. Atendimento com hora marcada para sua maior comodidade.',
    rua: 'Estrada do Rio Grande',
    numero: '120',
    bairro: 'Taquara',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21912345678',
    instagram: '@studiohairvip_jpa',
    business_hours: {
      segunda: { open: false, start: '09:00', end: '18:00' },
      terca: { open: true, start: '09:00', end: '19:00' },
      quarta: { open: true, start: '09:00', end: '19:00' },
      quinta: { open: true, start: '09:00', end: '19:00' },
      sexta: { open: true, start: '09:00', end: '20:00' },
      sabado: { open: true, start: '08:00', end: '20:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito'],
    recentComments: [
      'Minhas luzes ficaram perfeitas! Recomendo.',
      'Atendimento de primeira, muito atenciosos.',
      'Melhor salão da Taquara sem dúvidas.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=400&auto=format&fit=crop',
    verified: true
  },
  { 
    id: 'f-3', 
    name: 'Pet Shop Alegria', 
    category: 'Pets', 
    subcategory: 'Pet Shop', 
    rating: 4.7, 
    reviewsCount: 320,
    distance: 'Pechincha', 
    adType: AdType.PREMIUM, 
    description: 'Banho, tosa, veterinário e uma grande variedade de acessórios para o seu melhor amigo. Tratamos seu pet como se fosse nosso, com todo o carinho e cuidado que ele merece.',
    rua: 'Avenida Geremário Dantas',
    numero: '500',
    bairro: 'Pechincha',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21977778888',
    business_hours: {
      segunda: { open: true, start: '09:00', end: '18:00' },
      terca: { open: true, start: '09:00', end: '18:00' },
      quarta: { open: true, start: '09:00', end: '18:00' },
      quinta: { open: true, start: '09:00', end: '18:00' },
      sexta: { open: true, start: '09:00', end: '18:00' },
      sabado: { open: true, start: '09:00', end: '14:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro'],
    recentComments: [
      'A tosa ficou linda e meu cachorro saiu feliz.',
      'Dra. Paula é uma excelente veterinária.',
      'Preços justos e muita variedade de ração.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=400&auto=format&fit=crop',
    verified: true
  },
  { 
    id: 'f-4', 
    name: 'Mecânica 24h', 
    category: 'Autos', 
    subcategory: 'Oficinas Mecânicas', 
    rating: 4.5, 
    reviewsCount: 112,
    distance: 'Anil', 
    adType: AdType.PREMIUM, 
    description: 'Socorro mecânico especializado disponível 24 horas por dia. Reboque, recarga de bateria, troca de pneus e diagnósticos rápidos para que você não fique na mão.',
    rua: 'Estrada de Jacarepaguá',
    numero: '4200',
    bairro: 'Anil',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21955554444',
    business_hours: {
      segunda: { open: true, start: '00:00', end: '23:59' },
      terca: { open: true, start: '00:00', end: '23:59' },
      quarta: { open: true, start: '00:00', end: '23:59' },
      quinta: { open: true, start: '00:00', end: '23:59' },
      sexta: { open: true, start: '00:00', end: '23:59' },
      sabado: { open: true, start: '00:00', end: '23:59' },
      domingo: { open: true, start: '00:00', end: '23:59' },
    },
    payment_methods: ['Pix', 'Crédito', 'Dinheiro'],
    recentComments: [
      'Me salvaram às 3 da manhã na Linha Amarela.',
      'Serviço honesto e preço justo pela urgência.',
      'Mecânico muito experiente.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=400&auto=format&fit=crop' 
  },
  { 
    id: 'f-5', 
    name: 'Pizzaria do Zé', 
    category: 'Comida', 
    subcategory: 'Pizzarias', 
    rating: 4.6, 
    reviewsCount: 540,
    distance: 'Freguesia', 
    adType: AdType.PREMIUM, 
    description: 'A pizza mais crocante da Freguesia, feita no tradicional forno a lenha. Sabores clássicos e receitas exclusivas do mestre pizzaiolo Zé.',
    rua: 'Rua Araguaia',
    numero: '230',
    bairro: 'Freguesia',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21944443333',
    business_hours: {
      segunda: { open: true, start: '18:00', end: '23:30' },
      terca: { open: true, start: '18:00', end: '23:30' },
      quarta: { open: true, start: '18:00', end: '23:30' },
      quinta: { open: true, start: '18:00', end: '23:30' },
      sexta: { open: true, start: '18:00', end: '00:30' },
      sabado: { open: true, start: '18:00', end: '00:30' },
      domingo: { open: true, start: '18:00', end: '23:30' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro'],
    recentComments: [
      'Massa fininha e recheio caprichado.',
      'A de Calabresa com cebola é imbatível.',
      'Entrega sempre no prazo.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400&auto=format&fit=crop' 
  },
  { 
    id: 'f-6', 
    name: 'Açaí da Praça', 
    category: 'Comida', 
    subcategory: 'Doces & Sobremesas', 
    rating: 4.9, 
    reviewsCount: 920,
    distance: 'Tanque', 
    adType: AdType.PREMIUM, 
    description: 'O açaí mais cremoso e gelado da região. Diversas opções de acompanhamentos frescos e montagem do seu jeito. Refresque seu dia com o verdadeiro sabor do Norte.',
    rua: 'Praça do Tanque',
    numero: 's/n',
    bairro: 'Tanque',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21933332222',
    business_hours: {
      segunda: { open: true, start: '10:00', end: '21:00' },
      terca: { open: true, start: '10:00', end: '21:00' },
      quarta: { open: true, start: '10:00', end: '21:00' },
      quinta: { open: true, start: '10:00', end: '21:00' },
      sexta: { open: true, start: '10:00', end: '22:00' },
      sabado: { open: true, start: '10:00', end: '22:00' },
      domingo: { open: true, start: '10:00', end: '21:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro'],
    recentComments: [
      'Açaí puro e sem cristais de gelo.',
      'O creme de leite ninho deles é surreal!',
      'Ponto de encontro perfeito no Tanque.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?q=80&w=400&auto=format&fit=crop' 
  },
  { 
    id: 'f-7', 
    name: 'Drogaria JPA', 
    category: 'Farmácia', 
    subcategory: 'Medicamentos', 
    rating: 4.4, 
    reviewsCount: 205,
    distance: 'Freguesia', 
    adType: AdType.PREMIUM, 
    description: 'Ampla linha de medicamentos genéricos e de marca, além de perfumaria e cuidados pessoais. Entrega domiciliar rápida para toda a região de Jacarepaguá.',
    rua: 'Estrada dos Três Rios',
    numero: '1100',
    bairro: 'Freguesia',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21922221111',
    telefone_fixo_publico: '2133440000',
    business_hours: {
      segunda: { open: true, start: '07:00', end: '23:00' },
      terca: { open: true, start: '07:00', end: '23:00' },
      quarta: { open: true, start: '07:00', end: '23:00' },
      quinta: { open: true, start: '07:00', end: '23:00' },
      sexta: { open: true, start: '07:00', end: '23:00' },
      sabado: { open: true, start: '08:00', end: '22:00' },
      domingo: { open: true, start: '08:00', end: '20:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro'],
    recentComments: [
      'Sempre encontro o que preciso.',
      'O delivery é muito rápido mesmo.',
      'Farmacêuticos atenciosos.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbbb88?q=80&w=400&auto=format&fit=crop' 
  },
  { 
    id: 'f-8', 
    name: 'Academia FitBairro', 
    category: 'Esportes', 
    subcategory: 'Academias', 
    rating: 4.7, 
    reviewsCount: 380,
    distance: 'Taquara', 
    adType: AdType.PREMIUM, 
    description: 'Equipamentos modernos e professores dedicados para ajudar você a alcançar seus objetivos. Musculação, funcional e aulas coletivas em um ambiente motivador e climatizado.',
    rua: 'Rua Nelson Cardoso',
    numero: '800',
    bairro: 'Taquara',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21911110000',
    business_hours: {
      segunda: { open: true, start: '06:00', end: '22:00' },
      terca: { open: true, start: '06:00', end: '22:00' },
      quarta: { open: true, start: '06:00', end: '22:00' },
      quinta: { open: true, start: '06:00', end: '22:00' },
      sexta: { open: true, start: '06:00', end: '22:00' },
      sabado: { open: true, start: '08:00', end: '14:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito'],
    recentComments: [
      'Ótimo custo-benefício.',
      'Professores muito presentes na sala.',
      'Ambiente limpo e organizado.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=400&auto=format&fit=crop',
    verified: true
  },
  { 
    id: 'f-9', 
    name: 'Consultório Dra. Ana', 
    category: 'Saúde', 
    subcategory: 'Dentistas', 
    rating: 5.0, 
    reviewsCount: 65,
    distance: 'Freguesia', 
    adType: AdType.PREMIUM, 
    description: 'Odontologia moderna com foco no conforto do paciente. Clínica geral, ortodontia e estética dental com tecnologia de ponta para devolver o seu melhor sorriso.',
    rua: 'Rua Comendador Siqueira',
    numero: '350',
    bairro: 'Freguesia',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21900009999',
    business_hours: {
      segunda: { open: true, start: '09:00', end: '18:00' },
      terca: { open: true, start: '09:00', end: '18:00' },
      quarta: { open: true, start: '09:00', end: '18:00' },
      quinta: { open: true, start: '09:00', end: '18:00' },
      sexta: { open: true, start: '09:00', end: '17:00' },
      sabado: { open: false, start: '09:00', end: '14:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito'],
    recentComments: [
      'Extremamente cuidadosa e detalhista.',
      'Não senti dor nenhuma no tratamento.',
      'Consultório impecável.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=400&auto=format&fit=crop',
    verified: true
  },
  { 
    id: 'f-10', 
    name: 'Boutique Chic', 
    category: 'Moda', 
    subcategory: 'Moda Feminina', 
    rating: 4.3, 
    reviewsCount: 42,
    distance: 'Anil', 
    adType: AdType.PREMIUM, 
    description: 'Roupas e acessórios para mulheres que não abrem mão da elegância e do estilo. Peças selecionadas que acompanham as tendências da moda nacional e internacional.',
    rua: 'Estrada de Jacarepaguá',
    numero: '5000',
    bairro: 'Anil',
    cidade: 'Rio de Janeiro',
    whatsapp_publico: '21988887777',
    instagram: '@boutiquechic_jpa',
    business_hours: {
      segunda: { open: true, start: '10:00', end: '19:00' },
      terca: { open: true, start: '10:00', end: '19:00' },
      quarta: { open: true, start: '10:00', end: '19:00' },
      quinta: { open: true, start: '10:00', end: '19:00' },
      sexta: { open: true, start: '10:00', end: '19:00' },
      sabado: { open: true, start: '09:00', end: '18:00' },
      domingo: { open: false, start: '10:00', end: '14:00' },
    },
    payment_methods: ['Pix', 'Crédito', 'Débito', 'Dinheiro'],
    recentComments: [
      'Peças exclusivas e de ótima qualidade.',
      'O atendimento da vendedora Sheila foi ótimo.',
      'Sempre encontro looks lindos aqui.'
    ],
    isSponsored: true, 
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=400&auto=format&fit=crop' 
  },
];

export const EDITORIAL_SERVICES: EditorialCollection[] = [
  {
    id: 'culinaria-jpa',
    title: 'Melhores de JPA',
    subtitle: 'Onde comer bem no bairro',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop',
    keywords: ['comida', 'restaurante', 'lanches', 'pizza']
  },
  {
    id: 'servicos-confianca',
    title: 'Serviços de Confiança',
    subtitle: 'Profissionais avaliados por vizinhos',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop',
    keywords: ['serviços', 'reformas', 'consertos']
  }
];

export const quickFilters = [
  { id: 'top_rated', label: 'Top Avaliados', icon: 'star' },
  { id: 'open_now', label: 'Aberto Agora', icon: 'clock' },
  { id: 'nearby', label: 'Perto de Mim', icon: 'zap' },
  { id: 'cashback', label: 'Com Cashback', icon: 'percent' }
];

export const STORIES: Story[] = [
  { id: 's1', name: 'Hamburgueria', image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?q=80&w=400&auto=format&fit=crop' },
  { id: 's2', name: 'Salão Vip', image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=400&auto=format&fit=crop' },
  { id: 's3', name: 'Pet Shop', image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=400&auto=format&fit=crop' },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    role: 'Atendente de Balcão',
    company: 'Padaria Imperial',
    neighborhood: 'Freguesia',
    category: 'Alimentação',
    type: 'CLT',
    salary: 'R$ 1.450,00',
    description: 'Atendimento ao público, organization e limpeza do local.',
    requirements: ['Experiência anterior', 'Boa comunicação'],
    schedule: '6x1',
    contactWhatsapp: '5521999999999',
    postedAt: 'Há 2h',
    isSponsored: true,
    sponsoredUntil: '2025-12-31'
  },
  {
    id: 'job-2',
    role: 'Vendedor Externo',
    company: 'JPA Telecom',
    neighborhood: 'Taquara',
    category: 'Vendas',
    type: 'PJ',
    salary: 'Comissão + Ajuda de Custo',
    description: 'Vendas de planos de internet e TV a cabo.',
    requirements: ['Carro próprio', 'Experiência com vendas'],
    schedule: 'Seg-Sex',
    contactWhatsapp: '5521988888888',
    postedAt: 'Há 1 dia',
    isUrgent: true
  }
];

export type TaxonomyType = 'category' | 'subcategory' | 'specialty';

export const SPECIALTIES: Record<string, string[]> = {
  'Chaveiro 24h': ['Abertura de portas', 'Troca de fechadura', 'Chave codificada', 'Abertura de cofre', 'Cópia de chaves', 'Instalação de tetra chave'],
  'Desentupidora': ['Pia de cozinha', 'Vaso sanitário', 'Caixa de gordura', 'Ralo de banheiro', 'Rede de esgoto externa', 'Limpeza de fossa'],
  'Guincho': ['Reboque leve (carro)', 'Reboque pesado', 'Pane seca', 'Troca de pneu', 'Recarga de bateria'],
  'Eletricista 24h': ['Queda de energia total', 'Curto-circuito', 'Disjuntor desarmando', 'Cheiro de queimado', 'Tomada em curto'],
  'Eletricista': ['Instalação de chuveiro', 'Troca de fiação', 'Instalação de tomadas', 'Instalação de ventilador', 'Iluminação e lustres'],
  'Encanador': ['Vazamento em cano', 'Troca de torneira', 'Instalação de filtro', 'Reparo em descarga', 'Limpeza de caixa d\'água'],
  'Pedreiro': ['Pequenos reparos', 'Reboco e alvenaria', 'Colocação de piso/azulejo', 'Construção de muro', 'Reforma completa'],
  'Pintor': ['Pintura interna', 'Pintura externa', 'Texturas e efeitos', 'Tratamento de mofo', 'Pintura de portas e janelas'],
  'Marido de Aluguel': ['Instalação de cortina/persiana', 'Montagem de prateleiras', 'Troca de lâmpadas', 'Instalação de suporte de TV', 'Pequenos reparos gerais'],
  'Mecânico': ['Revisão geral', 'Troca de óleo', 'Suspensão e freios', 'Motor e câmbio', 'Diagnóstico eletrônico'],
  'Funilaria e Pintura': ['Martelinho de ouro', 'Polimento e cristalização', 'Pintura de peças', 'Reparo de para-choque'],
  'Auto Elétrica': ['Troca de bateria', 'Alternador e motor de arranque', 'Instalação de som/multimídia', 'Lâmpadas e faróis'],
  'Conserto de Celular': ['Troca de tela', 'Troca de bateria', 'Não carrega', 'Recuperação de sistema', 'Limpeza de água'],
  'Informática': ['Formatação', 'Remoção de vírus', 'Upgrade de memória/SSD', 'Limpeza interna', 'Configuração de rede'],
  'default': ['Consultoria', 'Orçamento geral', 'Manutenção preventiva', 'Reparo específico', 'Instalação']
};