
import React from 'react';
import { 
  Utensils, ShoppingCart, Scissors, Heart, PawPrint, Home, Wrench, 
  Dumbbell, CarFront, BookOpen, Monitor, Shirt, Ticket, Map as MapIcon, 
  Store as StoreIcon,
  LayoutGrid, Pill, Briefcase, Plane, Zap,
  Beef, Coffee, Pizza, Croissant, Soup, Cake, Sandwich, 
  Stethoscope, Package, Clock, Target, Settings, Dog,
  Star, Tag, Award, TrendingUp, ChevronRight, MessageSquare, Users,
  Apple, Building2, Leaf, Shield, PaintRoller, Hammer, Droplets, Laptop,
  Baby, GraduationCap, Microscope, Brain, Sparkles, Smile, Beer, 
  Activity, Eye, FileText, Globe, Calendar, Music, PartyPopper, Globe2, Edit3, User, Bell, Search,
  Camera, Vote, Handshake, Flame, Milestone, History, Home as HomeIcon,
  MessageCircle, HelpCircle, UserCheck, Recycle, Scale, Calculator, PenTool, Ruler,
  Key, Fan, Truck, Shovel,
  Meh, ThumbsDown, Gift, RefreshCw, Wind, Bike, Cpu,
  // Adicionados novos ícones para a lista de profissionais
  Wifi, Sun, Tent, Bug, Square, Phone, Newspaper, ShieldCheck, Lock, MapPin, Megaphone, Mic, Disc, Headphones, CheckCircle2, Palette
} from 'lucide-react';
import { AdType, Category, Store, Story, EditorialCollection, Job, CommunityPost, NeighborhoodCommunity, Classified, RealEstateProperty } from './types';
import { getStoreLogo } from '@/utils/mockLogos';


export const CATEGORIES: Category[] = [
  { id: 'cat-alimentacao', name: 'Alimentação', slug: 'alimentacao', icon: <Utensils />, color: 'bg-brand-blue' },
  { id: 'cat-pets', name: 'Pets', slug: 'pets', icon: <PawPrint />, color: 'bg-brand-blue' },
  { id: 'cat-pro', name: 'Profissionais', slug: 'profissionais', icon: <Briefcase />, color: 'bg-brand-blue' },
  { id: 'cat-saude', name: 'Saúde', slug: 'saude', icon: <Heart />, color: 'bg-brand-blue' },
  { id: 'cat-beauty', name: 'Beleza', slug: 'beleza', icon: <Scissors />, color: 'bg-brand-blue' },
  { id: 'cat-autos', name: 'Autos', slug: 'autos', icon: <CarFront />, color: 'bg-brand-blue' },
  { id: 'cat-mercado', name: 'Mercado', slug: 'mercado', icon: <ShoppingCart />, color: 'bg-brand-blue' },
  { id: 'cat-casa', name: 'Casa', slug: 'casa', icon: <HomeIcon />, color: 'bg-brand-blue' },
  { id: 'cat-sports', name: 'Esportes', slug: 'esportes', icon: <Dumbbell />, color: 'bg-brand-blue' },
  { id: 'cat-leisure', name: 'Lazer', slug: 'lazer', icon: <Ticket />, color: 'bg-brand-blue' },
  { id: 'cat-edu', name: 'Educação', slug: 'educacao', icon: <BookOpen />, color: 'bg-brand-blue' },
  { id: 'cat-pharmacy', name: 'Farmácia', slug: 'farmacia', icon: <Pill />, color: 'bg-brand-blue' },
  { id: 'cat-fashion', name: 'Moda', slug: 'moda', icon: <Shirt />, color: 'bg-brand-blue' },
  { id: 'cat-eventos', name: 'Eventos', slug: 'eventos', icon: <PartyPopper />, color: 'bg-brand-blue' },
  { id: 'cat-condominio', name: 'Condomínio', slug: 'condominio', icon: <Building2 />, color: 'bg-brand-blue' },
];

// --- NOVAS CONSTANTES PARA PROFISSIONAIS ---
const MANUAL_PROFESSIONALS_SUBCATEGORIES = [
    { name: 'Pedreiro', icon: <Hammer /> },
    { name: 'Eletricista', icon: <Zap /> },
    { name: 'Encanador', icon: <Droplets /> },
    { name: 'Bombeiro hidráulico', icon: <Wrench /> },
    { name: 'Pintor', icon: <PaintRoller /> },
    { name: 'Gesseiro', icon: <PaintRoller /> },
    { name: 'Marceneiro', icon: <Hammer /> },
    { name: 'Carpinteiro', icon: <Hammer /> },
    { name: 'Serralheiro', icon: <Settings /> },
    { name: 'Soldador', icon: <Flame /> },
    { name: 'Azulejista', icon: <Hammer /> },
    { name: 'Ladrilheiro', icon: <Hammer /> },
    { name: 'Telhadista', icon: <HomeIcon /> },
    { name: 'Calheiro', icon: <Droplets /> },
    { name: 'Vidraceiro', icon: <Square /> },
    { name: 'Impermeabilizador', icon: <Shield /> },
    { name: 'Instalador de drywall', icon: <Hammer /> },
    { name: 'Instalador de forro (gesso / PVC)', icon: <Hammer /> },
    { name: 'Instalador de pisos', icon: <Ruler /> },
    { name: 'Instalador de porcelanato', icon: <Ruler /> },
    { name: 'Instalador de laminado', icon: <Ruler /> },
    { name: 'Instalador de vinílico', icon: <Ruler /> },
    { name: 'Instalador de rodapé', icon: <Ruler /> },
    { name: 'Instalador de revestimentos', icon: <Hammer /> },
    { name: 'Instalador de box', icon: <Droplets /> },
    { name: 'Instalador de espelhos', icon: <Square /> },
    { name: 'Montador de móveis', icon: <Settings /> },
    { name: 'Desmontador de móveis', icon: <Settings /> },
    { name: 'Chaveiro', icon: <Key /> },
    { name: 'Instalador de portões', icon: <Building2 /> },
    { name: 'Instalador de grades', icon: <LayoutGrid /> },
    { name: 'Instalador de corrimão', icon: <Settings /> },
    { name: 'Instalador de cercas', icon: <Settings /> },
    { name: 'Instalador de cerca elétrica', icon: <Zap /> },
    { name: 'Instalador de concertina', icon: <Shield /> },
    { name: 'Instalador de alarmes residenciais', icon: <Bell /> },
    { name: 'Instalador de câmeras (CFTV)', icon: <Camera /> },
    { name: 'Técnico em manutenção predial', icon: <Wrench /> },
    { name: 'Técnico em pequenos reparos', icon: <Wrench /> },
    { name: 'Técnico de telhados', icon: <HomeIcon /> },
    { name: 'Técnico de impermeabilização', icon: <Shield /> },
    { name: 'Técnico em hidráulica', icon: <Droplets /> },
    { name: 'Técnico em elétrica residencial', icon: <Zap /> },
    { name: 'Desentupidor', icon: <Shovel /> },
    { name: 'Limpador de caixa d’água', icon: <Droplets /> },
    { name: 'Dedetizador', icon: <Bug /> },
    { name: 'Controlador de pragas', icon: <Bug /> },
    { name: 'Jardineiro', icon: <Leaf /> },
    { name: 'Paisagista', icon: <Leaf /> },
    { name: 'Piscineiro', icon: <Droplets /> },
    { name: 'Limpador de piscina', icon: <Droplets /> },
    { name: 'Podador de árvores', icon: <Scissors /> },
    { name: 'Operador de roçadeira', icon: <Fan /> },
    { name: 'Caseiro', icon: <HomeIcon /> },
    { name: 'Zelador', icon: <User /> },
    { name: 'Auxiliar de obras', icon: <User /> },
    { name: 'Mestre de obras', icon: <Briefcase /> },
    { name: 'Servente de obras', icon: <User /> },
    { name: 'Ajudante de pedreiro', icon: <User /> },
    { name: 'Instalador de antenas', icon: <Wifi /> },
    { name: 'Instalador de internet residencial', icon: <Wifi /> },
    { name: 'Instalador de ar-condicionado', icon: <Wind /> },
    { name: 'Técnico de refrigeração', icon: <Fan /> },
    { name: 'Instalador de coifas e exaustores', icon: <Fan /> },
    { name: 'Instalador de aquecedor a gás', icon: <Flame /> },
    { name: 'Instalador de energia solar residencial', icon: <Sun /> },
    { name: 'Instalador de toldos', icon: <Tent /> },
    { name: 'Instalador de persianas', icon: <LayoutGrid /> },
    { name: 'Instalador de cortinas', icon: <LayoutGrid /> },
    { name: 'Instalador de papel de parede', icon: <PaintRoller /> },
    { name: 'Instalador de papel vinílico', icon: <PaintRoller /> },
    { name: 'Limpador pós-obra', icon: <Sparkles /> },
    { name: 'Faxineiro de obra', icon: <Sparkles /> },
    { name: 'Lavador de fachadas', icon: <Droplets /> },
    { name: 'Pintor de fachadas', icon: <PaintRoller /> },
    { name: 'Restaurador de fachadas', icon: <PaintRoller /> },
];

const MANUAL_PROFESSIONALS_LIST = MANUAL_PROFESSIONALS_SUBCATEGORIES.map(s => s.name);

const TECHNICIAN_PROFESSIONALS_SUBCATEGORIES_FULL = [
    { name: 'Advogado', icon: <Scale /> },
    { name: 'Advogado trabalhista', icon: <Scale /> },
    { name: 'Advogado civil', icon: <Scale /> },
    { name: 'Advogado previdenciário', icon: <Scale /> },
    { name: 'Advogado imobiliário', icon: <Scale /> },
    { name: 'Advogado empresarial', icon: <Scale /> },
    { name: 'Advogado de família', icon: <Scale /> },
    { name: 'Contador', icon: <Calculator /> },
    { name: 'Contador fiscal', icon: <Calculator /> },
    { name: 'Técnico contábil', icon: <Calculator /> },
    { name: 'Auditor contábil', icon: <Calculator /> },
    { name: 'Consultor financeiro', icon: <Briefcase /> },
    { name: 'Consultor empresarial', icon: <Briefcase /> },
    { name: 'Consultor tributário', icon: <Briefcase /> },
    { name: 'Economista', icon: <Briefcase /> },
    { name: 'Despachante', icon: <FileText /> },
    { name: 'Despachante imobiliário', icon: <FileText /> },
    { name: 'Despachante veicular', icon: <FileText /> },
    { name: 'Corretor de imóveis', icon: <Key /> },
    { name: 'Avaliador imobiliário', icon: <Key /> },
    { name: 'Síndico profissional', icon: <Building2 /> },
    { name: 'Administrador de condomínios', icon: <Building2 /> },
    { name: 'Gestor condominial', icon: <Building2 /> },
    { name: 'Professor particular', icon: <User /> },
    { name: 'Tutor escolar', icon: <User /> },
    { name: 'Reforço escolar', icon: <User /> },
    { name: 'Professor de idiomas', icon: <User /> },
    { name: 'Professor de informática', icon: <User /> },
    { name: 'Instrutor de cursos livres', icon: <User /> },
    { name: 'Designer gráfico', icon: <PenTool /> },
    { name: 'Designer digital', icon: <PenTool /> },
    { name: 'Web designer', icon: <PenTool /> },
    { name: 'UX/UI designer', icon: <PenTool /> },
    { name: 'Desenvolvedor web', icon: <Laptop /> },
    { name: 'Programador', icon: <Laptop /> },
    { name: 'Analista de sistemas', icon: <Laptop /> },
    { name: 'Técnico em informática', icon: <Laptop /> },
    { name: 'Técnico em redes', icon: <Laptop /> },
    { name: 'Técnico em manutenção de computadores', icon: <Laptop /> },
    { name: 'Técnico em celulares', icon: <Phone /> },
    { name: 'Técnico em notebooks', icon: <Laptop /> },
    { name: 'Técnico em impressoras', icon: <FileText /> },
    { name: 'Técnico em TI residencial', icon: <Laptop /> },
    { name: 'Consultor de tecnologia', icon: <Laptop /> },
    { name: 'Especialista em segurança da informação', icon: <Shield /> },
    { name: 'Analista de dados', icon: <Calculator /> },
    { name: 'Social media', icon: <Megaphone /> },
    { name: 'Gestor de tráfego pago', icon: <TrendingUp /> },
    { name: 'Especialista em marketing digital', icon: <Megaphone /> },
    { name: 'Copywriter', icon: <Edit3 /> },
    { name: 'Produtor de conteúdo', icon: <Edit3 /> },
    { name: 'Fotógrafo', icon: <Camera /> },
    { name: 'Videomaker', icon: <Camera /> },
    { name: 'Editor de vídeo', icon: <Camera /> },
    { name: 'Motion designer', icon: <Camera /> },
    { name: 'Produtor audiovisual', icon: <Camera /> },
    { name: 'Jornalista freelancer', icon: <Newspaper /> },
    { name: 'Redator', icon: <Edit3 /> },
    { name: 'Revisor de texto', icon: <Edit3 /> },
    { name: 'Tradutor', icon: <Globe2 /> },
    { name: 'Intérprete', icon: <Globe2 /> },
    { name: 'Publicitário', icon: <Megaphone /> },
    { name: 'Relações públicas', icon: <Megaphone /> },
    { name: 'Coach', icon: <UserCheck /> },
    { name: 'Mentor profissional', icon: <UserCheck /> },
    { name: 'Orientador de carreira', icon: <UserCheck /> },
    { name: 'Psicopedagogo', icon: <Brain /> },
    { name: 'Psicólogo organizacional', icon: <Brain /> },
    { name: 'Terapeuta ocupacional', icon: <Activity /> },
    { name: 'Fonoaudiólogo', icon: <MessageSquare /> },
    { name: 'Nutricionista (consultoria)', icon: <Apple /> },
    { name: 'Personal trainer', icon: <Dumbbell /> },
    { name: 'Consultor de saúde', icon: <Heart /> },
    { name: 'Massoterapeuta', icon: <User /> },
    { name: 'Quiropraxista', icon: <User /> },
    { name: 'Acupunturista', icon: <User /> },
    { name: 'Esteticista (técnico)', icon: <Sparkles /> },
    { name: 'Podólogo', icon: <Sparkles /> },
    { name: 'Técnico em segurança do trabalho', icon: <Shield /> },
    { name: 'Engenheiro civil', icon: <Wrench /> },
    { name: 'Engenheiro eletricista', icon: <Zap /> },
    { name: 'Engenheiro mecânico', icon: <Wrench /> },
    { name: 'Arquiteto', icon: <Ruler /> },
    { name: 'Urbanista', icon: <Ruler /> },
    { name: 'Topógrafo', icon: <MapPin /> },
    { name: 'Técnico em edificações', icon: <Wrench /> },
    { name: 'Técnico em eletrotécnica', icon: <Zap /> },
    { name: 'Técnico em automação', icon: <Settings /> },
    { name: 'Perito técnico', icon: <Search /> },
    { name: 'Perito judicial', icon: <Search /> },
    { name: 'Avaliador técnico', icon: <Search /> },
    { name: 'Técnico em laudos e vistorias', icon: <Search /> },
    { name: 'Técnico em meio ambiente', icon: <Leaf /> },
    { name: 'Consultor ambiental', icon: <Leaf /> },
    { name: 'Gestor de projetos', icon: <Briefcase /> },
    { name: 'Product manager', icon: <Briefcase /> },
    { name: 'Analista de processos', icon: <Briefcase /> },
    { name: 'Analista de qualidade', icon: <Briefcase /> },
    { name: 'Especialista em compliance', icon: <ShieldCheck /> },
    { name: 'Consultor jurídico', icon: <Scale /> },
    { name: 'Técnico em licitações', icon: <FileText /> },
    { name: 'Especialista em contratos', icon: <FileText /> },
    { name: 'Despachante aduaneiro', icon: <Plane /> },
    { name: 'Consultor de comércio exterior', icon: <Plane /> },
    { name: 'Agente de viagens', icon: <Plane /> },
    { name: 'Consultor de turismo', icon: <Plane /> },
    { name: 'Planejador financeiro', icon: <Calculator /> },
    { name: 'Corretor de seguros', icon: <ShieldCheck /> },
    { name: 'Consultor de seguros', icon: <ShieldCheck /> },
    { name: 'Atuário', icon: <Calculator /> },
    { name: 'Especialista em benefícios', icon: <Gift /> },
    { name: 'Técnico administrativo', icon: <FileText /> },
    { name: 'Assistente virtual', icon: <FileText /> },
    { name: 'Secretário(a) remoto(a)', icon: <FileText /> },
    { name: 'Digitador', icon: <FileText /> },
    { name: 'Analista de dados administrativos', icon: <FileText /> },
    { name: 'Especialista em LGPD', icon: <Lock /> },
    { name: 'Encarregado de dados (DPO)', icon: <Lock /> },
];

const TECHNICIAN_PROFESSIONALS_LIST_FULL = TECHNICIAN_PROFESSIONALS_SUBCATEGORIES_FULL.map(s => s.name);
// --- FIM DAS NOVAS CONSTANTES ---

// --- NOVA ESTRUTURA PARA ALIMENTAÇÃO ---
export const FOOD_GROUPS = [
  // 7 principais visíveis na Home
  { name: 'Restaurantes', icon: <Utensils /> },
  { name: 'Lanches', icon: <Beef /> },
  { name: 'Massas', icon: <Pizza /> },
  { name: 'Brasileira', icon: <Soup /> },
  { name: 'Culinária Internacional', icon: <Globe /> },
  { name: 'Cafés', icon: <Coffee /> },
  { name: 'Doces', icon: <Cake /> },
  // Restante para o modal "+ Mais"
  { name: 'Bebidas', icon: <Beer /> },
  { name: 'Sobremesas', icon: <Cake /> },
  { name: 'Gelados', icon: <Sparkles /> },
  { name: 'Saudável', icon: <Leaf /> },
  { name: 'Marmitas', icon: <Package /> },
  { name: 'Padaria', icon: <Croissant /> },
  { name: 'Bares', icon: <Beer /> },
  { name: 'Eventos', icon: <PartyPopper /> },
  { name: 'Comida para Nichos', icon: <Target /> },
];

export const FOOD_SUB_SUB_CATEGORIES: Record<string, string[]> = {
  'Restaurantes': ['Restaurante tradicional', 'Restaurante executivo', 'Restaurante self-service', 'Restaurante por quilo', 'Restaurante à la carte', 'Restaurante buffet', 'Restaurante familiar', 'Cozinha caseira', 'Cozinha autoral'],
  'Lanches': ['Lanchonete', 'Hamburgueria', 'Hambúrguer artesanal', 'Hot dog', 'Sanduíches naturais', 'Fast food', 'Food truck'],
  'Massas': ['Pizzaria', 'Pizzaria artesanal', 'Massas artesanais', 'Cantina italiana', 'Lasanha', 'Nhoque', 'Macarrão'],
  'Brasileira': ['Comida brasileira', 'Comida nordestina', 'Comida mineira', 'Comida baiana', 'Feijoada', 'Churrasco', 'Espetinho'],
  'Culinária Internacional': ['Japonesa / Sushi', 'Chinesa', 'Árabe', 'Mexicana', 'Italiana', 'Francesa', 'Portuguesa', 'Peruana'],
  'Bebidas': ['Sucos naturais', 'Smoothies', 'Vitaminas', 'Bebidas geladas', 'Bebidas naturais'],
  'Cafés': ['Cafeteria', 'Café gourmet', 'Café colonial', 'Casa de chá'],
  'Doces': ['Doceria', 'Bolos', 'Bolos caseiros', 'Bolos decorados', 'Brigadeiro gourmet', 'Doces finos'],
  'Sobremesas': ['Tortas doces', 'Brownies', 'Cupcakes', 'Donuts', 'Churros'],
  'Gelados': ['Sorveteria', 'Gelateria', 'Açaí', 'Açaíteria', 'Frozen yogurt', 'Milk-shake', 'Picolé artesanal'],
  'Saudável': ['Comida saudável', 'Fit food', 'Vegano', 'Vegetariano', 'Low carb', 'Sem glúten', 'Sem lactose'],
  'Marmitas': ['Marmitex', 'Marmita caseira', 'Marmita fitness', 'Marmita congelada', 'Prato feito (PF)', 'Refeições prontas'],
  'Padaria': ['Padaria tradicional', 'Padaria artesanal', 'Padaria 24h', 'Empório', 'Empório gourmet'],
  'Bares': ['Bar', 'Barzinho', 'Boteco', 'Petiscos', 'Porções', 'Caldos', 'Sopas', 'Cervejaria artesanal'],
  'Eventos': ['Buffet', 'Buffet infantil', 'Buffet corporativo', 'Coffee break', 'Catering', 'Chef em domicílio'],
  'Comida para Nichos': ['Comida infantil', 'Papinhas', 'Comida para idosos', 'Comida para atletas', 'Comida para diabéticos'],
};
// --- FIM DA ESTRUTURA DE ALIMENTAÇÃO ---

// --- NOVA ESTRUTURA PARA PETS ---
export const ALL_PETS_GROUPS = [
  { name: 'Veterinários', icon: <Stethoscope /> },
  { name: 'Pet Shop', icon: <ShoppingCart /> },
  { name: 'Banho & Tosa', icon: <Scissors /> },
  { name: 'Adestramento', icon: <Award /> },
  { name: 'Hospedagem & Creche', icon: <HomeIcon /> },
  { name: 'Cuidados & Serviços', icon: <Heart /> },
  { name: 'Produtos Pet', icon: <Package /> },
  { name: 'Passeadores (Dog Walker)', icon: <Users /> },
  { name: 'Pets Exóticos', icon: <Sparkles /> },
  { name: 'Fotografia Pet', icon: <Camera /> },
  { name: 'Plano de Saúde Pet', icon: <ShieldCheck /> },
];

// Primeiros 7 para a tela principal
export const PETS_GROUPS = ALL_PETS_GROUPS.slice(0, 7);
// --- FIM DA ESTRUTURA DE PETS ---

// FIX: Added missing constants for 'Beleza' category.
// --- ESTRUTURA PARA BELEZA ---
export const BELEZA_GROUPS = [
  { name: 'Cabelos', icon: <Scissors /> },
  { name: 'Unhas', icon: <Star /> },
  { name: 'Estética', icon: <Sparkles /> },
  { name: 'Sobrancelhas & Cílios', icon: <Eye /> },
  { name: 'Barbearia', icon: <User /> },
  { name: 'Depilação', icon: <Wind /> },
  { name: 'Maquiagem & Eventos', icon: <Palette /> },
];

export const BELEZA_SUB_SUB_CATEGORIES: Record<string, string[]> = {
  'Cabelos': ['Salão de beleza', 'Cabeleireiro(a)', 'Corte feminino', 'Corte masculino', 'Escova', 'Hidratação', 'Coloração', 'Mechas / Luzes', 'Progressiva / Alisamento'],
  'Unhas': ['Manicure', 'Pedicure', 'Esmalteria', 'Unhas em gel', 'Unhas acrílicas', 'Alongamento de unhas', 'Nail designer'],
  'Estética': ['Estética facial', 'Estética corporal', 'Limpeza de pele', 'Peeling', 'Rejuvenescimento', 'Tratamentos corporais', 'Drenagem linfática', 'Massagem estética'],
  'Sobrancelhas & Cílios': ['Design de sobrancelhas', 'Micropigmentação', 'Henna', 'Extensão de cílios', 'Lash lifting', 'Brow lamination'],
  'Barbearia': ['Barbearia', 'Corte masculino', 'Barba', 'Barba terapêutica', 'Barbearia premium'],
  'Depilação': ['Depilação a cera', 'Depilação egípcia', 'Depilação a laser', 'Depilação masculina', 'Depilação feminina'],
  'Maquiagem & Eventos': ['Maquiagem social', 'Maquiagem profissional', 'Maquiagem para eventos', 'Dia da noiva', 'Dia do noivo', 'Produção para festas'],
};

export const ALL_BELEZA_SUBCATEGORIES = Object.values(BELEZA_SUB_SUB_CATEGORIES).flat();
// --- FIM DA ESTRUTURA DE BELEZA ---


export const SUBCATEGORIES: Record<string, { name: string; icon: React.ReactNode }[]> = {
  'Alimentação': FOOD_GROUPS,
  'Eventos': [
    { name: 'Eventos no Bairro', icon: <MapIcon /> },
    { name: 'Festas & Comemorações', icon: <PartyPopper /> },
    { name: 'Feiras & Exposições', icon: <StoreIcon /> },
    { name: 'Eventos Gastronômicos', icon: <Utensils /> },
    { name: 'Eventos Culturais', icon: <Music /> },
    { name: 'Eventos Esportivos', icon: <Dumbbell /> },
    { name: 'Eventos Infantis', icon: <Baby /> },
    { name: 'Eventos em Condomínio', icon: <Building2 /> },
  ],
  'Pets': ALL_PETS_GROUPS,
  'Profissionais': [
    ...MANUAL_PROFESSIONALS_SUBCATEGORIES,
    ...TECHNICIAN_PROFESSIONALS_SUBCATEGORIES_FULL
  ],
  'Saúde': [
    // Gerais
    { name: 'Clínicas', icon: <Building2 /> },
    { name: 'Dentistas', icon: <Smile /> },
    { name: 'Psicologia', icon: <Brain /> },
    { name: 'Fisioterapia', icon: <Activity /> },
    { name: 'Exames e Diagnósticos', icon: <Microscope /> },
    { name: 'Nutrição', icon: <Apple /> },
    { name: 'Terapias Alternativas', icon: <Sparkles /> },
    { name: 'Saúde Preventiva', icon: <Shield /> },
    { name: 'Vacinação', icon: <Stethoscope /> },
    // Específicas Mulher
    { name: 'Ginecologia', icon: <User /> },
    { name: 'Obstetrícia', icon: <Baby /> },
    { name: 'Dermatologia', icon: <Sparkles /> },
    { name: 'Endocrinologia', icon: <Activity /> },
    { name: 'Clínica médica', icon: <Stethoscope /> },
    { name: 'Cardiologia', icon: <Heart /> },
    { name: 'Ginecologia obstétrica', icon: <Stethoscope /> },
    { name: 'Mastologia', icon: <Stethoscope /> },
    { name: 'Fisioterapia pélvica', icon: <Activity /> },
    { name: 'Reprodução humana', icon: <Baby /> },
    { name: 'Planejamento familiar', icon: <Users /> },
    { name: 'Pré-natal', icon: <Baby /> },
    { name: 'Pós-parto', icon: <User /> },
    { name: 'Saúde da mulher', icon: <User /> },
    { name: 'Check-up feminino', icon: <UserCheck /> },
    { name: 'Dermatologia estética', icon: <Sparkles /> },
    { name: 'Ultrassonografia', icon: <Activity /> },
    // Específicas Homem
    { name: 'Urologia', icon: <User /> },
    { name: 'Ortopedia', icon: <Activity /> },
    { name: 'Traumatologia', icon: <Activity /> },
    { name: 'Psiquiatria', icon: <Brain /> },
    { name: 'Otorrinolaringologia', icon: <Mic /> },
    { name: 'Oftalmologia', icon: <Eye /> },
    { name: 'Gastroenterologia', icon: <Stethoscope /> },
    { name: 'Proctologia', icon: <Stethoscope /> },
    { name: 'Pneumologia', icon: <Stethoscope /> },
    { name: 'Reumatologia', icon: <Stethoscope /> },
    { name: 'Nefrologia', icon: <Stethoscope /> },
    { name: 'Angiologia', icon: <Stethoscope /> },
    { name: 'Medicina do esporte', icon: <Dumbbell /> },
    { name: 'Sexologia', icon: <Heart /> },
    { name: 'Check-up masculino', icon: <UserCheck /> },
    // Comuns a ambos e Pediatria
    { name: 'Exames laboratoriais', icon: <Microscope /> },
    { name: 'Exames de imagem', icon: <Camera /> },
    { name: 'Acupuntura', icon: <Sparkles /> },
    { name: 'Quiropraxia', icon: <User /> },
    { name: 'Terapias integrativas', icon: <Sparkles /> },
    { name: 'Fonoaudiologia', icon: <MessageSquare /> },
    { name: 'Enfermagem domiciliar', icon: <HomeIcon /> },
    { name: 'Cuidados pós-operatórios', icon: <Stethoscope /> },
    // Específicas Pediatria
    { name: 'Pediatria', icon: <Baby /> },
    { name: 'Neonatologia', icon: <Baby /> },
    { name: 'Puericultura', icon: <Baby /> },
    { name: 'Clínica infantil', icon: <Stethoscope /> },
    { name: 'Psicologia infantil', icon: <Brain /> },
    { name: 'Psicopedagogia', icon: <Brain /> },
    { name: 'Fonoaudiologia infantil', icon: <MessageSquare /> },
    { name: 'Nutrição infantil', icon: <Apple /> },
    { name: 'Odontopediatria', icon: <Smile /> },
    { name: 'Fisioterapia pediátrica', icon: <Activity /> },
    { name: 'Terapia ocupacional infantil', icon: <Activity /> },
    { name: 'Neuropediatria', icon: <Brain /> },
    { name: 'Psiquiatria infantil', icon: <Brain /> },
    { name: 'Endocrinologia pediátrica', icon: <Activity /> },
    { name: 'Alergologia pediátrica', icon: <Stethoscope /> },
    { name: 'Pneumologia pediátrica', icon: <Stethoscope /> },
    { name: 'Gastroenterologia pediátrica', icon: <Stethoscope /> },
    { name: 'Cardiologia pediátrica', icon: <Heart /> },
    { name: 'Dermatologia pediátrica', icon: <Sparkles /> },
    { name: 'Oftalmologia infantil', icon: <Eye /> },
    { name: 'Otorrinolaringologia infantil', icon: <Mic /> },
    { name: 'Enfermagem pediátrica', icon: <HomeIcon /> },
    { name: 'Exames laboratoriais infantis', icon: <Microscope /> },
    { name: 'Exames de imagem infantis', icon: <Camera /> },
    { name: 'Acompanhamento do desenvolvimento', icon: <TrendingUp /> },
    { name: 'Estimulação precoce', icon: <Zap /> },
    { name: 'Atendimento domiciliar pediátrico', icon: <HomeIcon /> },
  ],
  'Serviços': [
    { name: 'Limpeza Residencial', icon: <Sparkles /> },
    { name: 'Dedetização', icon: <Shield /> },
    { name: 'Manutenção Geral', icon: <Settings /> },
    { name: 'Chaveiro', icon: <Zap /> },
    { name: 'Segurança', icon: <Shield /> },
    { name: 'Serviços Rápidos', icon: <Zap /> },
    { name: 'Assistência Técnica', icon: <Monitor /> },
    { name: 'Instalações', icon: <Wrench /> },
  ],
  'Beleza': [
    { name: 'Salão de Cabelo', icon: <Scissors /> },
    { name: 'Barbearia', icon: <Scissors /> },
    { name: 'Manicure & Pedicure', icon: <Star /> },
    { name: 'Estética Facial', icon: <Sparkles /> },
    { name: 'Estética Corporal', icon: <Activity /> },
    { name: 'Maquiagem', icon: <Star /> },
    { name: 'Sobrancelhas & Cílios', icon: <Eye /> },
    { name: 'Spa & Relaxamento', icon: <Heart /> },
  ],
  'Autos': [
    // CARRO
    { name: 'Oficina mecânica', icon: <Wrench /> },
    { name: 'Autoelétrica', icon: <Zap /> },
    { name: 'Funilaria e pintura', icon: <PaintRoller /> },
    { name: 'Alinhamento e balanceamento', icon: <Settings /> },
    { name: 'Suspensão e freios', icon: <Disc /> },
    { name: 'Troca de óleo', icon: <Droplets /> },
    { name: 'Ar-condicionado automotivo', icon: <Wind /> },
    { name: 'Guincho e reboque', icon: <Truck /> },
    { name: 'Vidraçaria automotiva', icon: <Square /> },
    { name: 'Inspeção veicular', icon: <Search /> },
    { name: 'Lava-jato', icon: <Droplets /> },
    { name: 'Estética automotiva', icon: <Sparkles /> },
    { name: 'Instalação de som e acessórios', icon: <Headphones /> },
    // MOTO
    { name: 'Oficina de motos', icon: <Bike /> },
    { name: 'Mecânica de motos', icon: <Wrench /> },
    { name: 'Elétrica de motos', icon: <Zap /> },
    { name: 'Revisão', icon: <CheckCircle2 /> },
    { name: 'Suspensão', icon: <Settings /> },
    { name: 'Freios', icon: <Disc /> },
    { name: 'Escapamentos', icon: <Settings /> },
    { name: 'Acessórios', icon: <Package /> },
    { name: 'Lava-jato de motos', icon: <Droplets /> },
    { name: 'Guincho para motos', icon: <Truck /> },
    // UTILITÁRIOS
    { name: 'Oficina para vans e furgões', icon: <Truck /> },
    { name: 'Mecânica diesel', icon: <Wrench /> },
    { name: 'Autoelétrica pesada', icon: <Zap /> },
    { name: 'Suspensão reforçada', icon: <Settings /> },
    { name: 'Alinhamento', icon: <Settings /> },
    { name: 'Baú e carroceria', icon: <Truck /> },
    { name: 'Adaptações comerciais', icon: <Briefcase /> },
    // BICICLETAS
    { name: 'Oficina de bicicletas', icon: <Bike /> },
    { name: 'Manutenção geral', icon: <Wrench /> },
    { name: 'Ajuste de marchas', icon: <Settings /> },
    { name: 'Bicicletas elétricas', icon: <Zap /> },
    { name: 'Venda de peças', icon: <Package /> },
    { name: 'Customização', icon: <Palette /> },
  ].filter((v, i, a) => a.findIndex(t => (t.name === v.name)) === i), // De-duplicate by name
  'Mercado': [
    { name: 'Supermercados', icon: <ShoppingCart /> },
    { name: 'Mercados de Bairro', icon: <HomeIcon /> },
    { name: 'Atacarejo', icon: <Package /> },
    { name: 'Conveniência', icon: <Clock /> },
    { name: 'Produtos Importados', icon: <Globe /> },
    { name: 'Bebidas', icon: <Beer /> },
    { name: 'Produtos Congelados', icon: <Package /> },
    { name: 'Assinaturas & Cestas', icon: <Calendar /> },
  ],
  'Casa': [
    { name: 'Materiais de Construção', icon: <Hammer /> },
    { name: 'Decoração', icon: <Sparkles /> },
    { name: 'Iluminação', icon: <Zap /> },
    { name: 'Móveis', icon: <HomeIcon /> },
    { name: 'Eletrodomésticos', icon: <Monitor /> },
    { name: 'Jardinagem', icon: <Leaf /> },
    { name: 'Organização', icon: <LayoutGrid /> },
    { name: 'Reforma & Obras', icon: <Hammer /> },
  ],
  'Esportes': [
    { name: 'Academias', icon: <Dumbbell /> },
    { name: 'Personal Trainer', icon: <Users /> },
    { name: 'Esportes Coletivos', icon: <Users /> },
    { name: 'Artes Marciais', icon: <Target /> },
    { name: 'Yoga & Pilates', icon: <Activity /> },
    { name: 'Dança', icon: <Music /> },
    { name: 'Treino Funcional', icon: <Zap /> },
    { name: 'Esportes ao Ar Livre', icon: <Plane /> },
  ],
  'Lazer': [
    { name: 'Eventos', icon: <PartyPopper /> },
    { name: 'Shows & Música', icon: <Music /> },
    { name: 'Cinema & Teatro', icon: <Ticket /> },
    { name: 'Bares & Baladas', icon: <Beer /> },
    { name: 'Passeios', icon: <MapIcon /> },
    { name: 'Turismo Local', icon: <Globe2 /> },
    { name: 'Experiências', icon: <Sparkles /> },
    { name: 'Atividades em Família', icon: <Users /> },
  ],
  'Educação': [
    { name: 'Escolas', icon: <Building2 /> },
    { name: 'Cursos Livres', icon: <GraduationCap /> },
    { name: 'Idiomas', icon: <Globe2 /> },
    { name: 'Reforço Escolar', icon: <Edit3 /> },
    { name: 'Aulas Particulares', icon: <User /> },
    { name: 'Educação Infantil', icon: <Baby /> },
    { name: 'Cursos Profissionalizantes', icon: <Briefcase /> },
    { name: 'Tecnologia & Programação', icon: <Laptop /> },
  ],
  'Farmácia': [
    { name: 'Medicamentos', icon: <Pill /> },
    { name: 'Genéricos', icon: <Tag /> },
    { name: 'Manipulação', icon: <Microscope /> },
    { name: 'Perfumaria', icon: <Star /> },
    { name: 'Higiene & Cuidados', icon: <Heart /> },
    { name: 'Testes Rápidos', icon: <Zap /> },
    { name: 'Suplementos', icon: <Dumbbell /> },
    { name: 'Delivery Farmácia', icon: <Package /> },
  ],
  'Moda': [
    { name: 'Moda Feminina', icon: <Shirt /> },
    { name: 'Moda Masculina', icon: <Shirt /> },
    { name: 'Moda Infantil', icon: <Baby /> },
    { name: 'Calçados', icon: <Star /> },
    { name: 'Acessórios', icon: <Star /> },
    { name: 'Moda Íntima', icon: <Heart /> },
    { name: 'Moda Fitness', icon: <Dumbbell /> },
    { name: 'Brechós', icon: <Tag /> },
  ],
  'Condomínio': [
    { name: 'Avisos & Comunicados', icon: <Bell /> },
    { name: 'Serviços para Condomínio', icon: <Wrench /> },
    { name: 'Manutenção Predial', icon: <Hammer /> },
    { name: 'Segurança Condominial', icon: <Shield /> },
    { name: 'Limpeza & Portaria', icon: <Building2 /> },
    { name: 'Indicações de Profissionais', icon: <Users /> },
    { name: 'Eventos do Condomínio', icon: <Calendar /> },
    { name: 'Achados & Perdidos', icon: <Search /> },
  ],
};

export const HEALTH_GROUPS = {
  mulher: [
    'Clínica médica',  
    'Ginecologia',  
    'Obstetrícia',  
    'Ginecologia obstétrica',  
    'Mastologia',  
    'Endocrinologia',  
    'Cardiologia',  
    'Dermatologia',  
    'Fisioterapia',  
    'Fisioterapia pélvica',  
    'Psicologia',  
    'Psiquiatria',  
    'Nutrição',  
    'Reprodução humana',  
    'Planejamento familiar',  
    'Pré-natal',  
    'Pós-parto',  
    'Saúde da mulher',  
    'Check-up feminino',  
    'Sexologia',  
    'Dermatologia estética',  
    'Exames laboratoriais',  
    'Exames de imagem',  
    'Ultrassonografia',  
    'Acupuntura',  
    'Quiropraxia',  
    'Terapias integrativas',  
    'Fonoaudiologia',  

    'Enfermagem domiciliar',  
    'Cuidados pós-operatórios'
  ],
  homem: [
    'Clínica médica',  
    'Urologia',  
    'Cardiologia',  
    'Ortopedia',  
    'Traumatologia',  
    'Fisioterapia',  
    'Psicologia',  
    'Psiquiatria',  
    'Nutrição',  
    'Endocrinologia',  
    'Dermatologia',  
    'Otorrinolaringologia',  
    'Oftalmologia',  
    'Gastroenterologia',  
    'Proctologia',  
    'Pneumologia',  
    'Reumatologia',  
    'Nefrologia',  
    'Angiologia',  
    'Medicina do esporte',  
    'Sexologia',  
    'Check-up masculino',  
    'Exames laboratoriais',  
    'Exames de imagem',  
    'Acupuntura',  
    'Quiropraxia',  
    'Terapias integrativas',  
    'Fonoaudiologia',  
    'Enfermagem domiciliar',  
    'Cuidados pós-operatórios'
  ],
  pediatria: [
    'Pediatria',  
    'Neonatologia',  
    'Puericultura',  
    'Clínica infantil',  
    'Psicologia infantil',  
    'Psicopedagogia',  
    'Fonoaudiologia infantil',  
    'Nutrição infantil',  
    'Odontopediatria',  
    'Fisioterapia pediátrica',  
    'Terapia ocupacional infantil',  
    'Neuropediatria',  
    'Psiquiatria infantil',  
    'Endocrinologia pediátrica',  
    'Alergologia pediátrica',  
    'Pneumologia pediátrica',  
    'Gastroenterologia pediátrica',  
    'Cardiologia pediátrica',  
    'Dermatologia pediátrica',  
    'Oftalmologia infantil',  
    'Otorrinolaringologia infantil',  
    'Vacinação',  
    'Enfermagem pediátrica',  
    'Exames laboratoriais infantis',  
    'Exames de imagem infantis',  
    'Acompanhamento do desenvolvimento',  
    'Estimulação precoce',  
    'Atendimento domiciliar pediátrico'
  ],
};

export const PROFESSIONALS_GROUPS = {
  manuais: MANUAL_PROFESSIONALS_LIST,
  tecnicos: TECHNICIAN_PROFESSIONALS_LIST_FULL,
};

export const AUTOS_GROUPS = {
  carro: ['Oficina mecânica', 'Autoelétrica', 'Funilaria e pintura', 'Alinhamento e balanceamento', 'Suspensão e freios', 'Troca de óleo', 'Ar-condicionado automotivo', 'Guincho e reboque', 'Vidraçaria automotiva', 'Inspeção veicular', 'Lava-jato', 'Estética automotiva', 'Instalação de som e acessórios'],
  moto: ['Oficina de motos', 'Mecânica de motos', 'Elétrica de motos', 'Troca de óleo', 'Revisão', 'Suspensão', 'Freios', 'Escapamentos', 'Acessórios', 'Lava-jato de motos', 'Guincho para motos'],
  utilitarios: ['Oficina para vans e furgões', 'Mecânica diesel', 'Autoelétrica pesada', 'Suspensão reforçada', 'Freios', 'Troca de óleo', 'Alinhamento', 'Reboque e guincho', 'Baú e carroceria', 'Adaptações comerciais'],
  bicicletas: ['Oficina de bicicletas', 'Manutenção geral', 'Revisão', 'Ajuste de marchas', 'Freios', 'Suspensão', 'Bicicletas elétricas', 'Venda de peças', 'Acessórios', 'Customização'],
};

// FIX: Added ALL_TAGS to be exported from this file.
// 🔹 LISTA DE 60 TAGS INICIAIS (OBRIGATÓRIAS)
export const ALL_TAGS = [
  // 👕 MODA
  'tênis', 'camisa', 'camiseta', 'calça', 'bermuda', 'vestido', 'saia', 'moletom', 'jaqueta', 'roupa social', 'roupa feminina', 'roupa masculina',
  // ⌚ ACESSÓRIOS
  'relógio', 'óculos', 'bolsa', 'mochila', 'cinto', 'pulseira', 'colar', 'boné',
  // 🐶 PET
  'ração', 'banho e tosa', 'brinquedo pet', 'coleira', 'petiscos', 'veterinário', 'adestramento', 'transporte pet',
  // 🧴 BELEZA
  'corte de cabelo', 'manicure', 'pedicure', 'maquiagem', 'estética facial', 'sobrancelha', 'depilação', 'hidratação capilar',
  // 🚗 AUTOS
  'troca de óleo', 'alinhamento', 'balanceamento', 'revisão automotiva', 'lava jato', 'auto elétrica', 'funilaria', 'vistoria veicular',
  // 🏥 SAÚDE
  'clínica médica', 'dentista', 'psicologia', 'fisioterapia', 'exames laboratoriais', 'nutrição', 'terapias alternativas', 'saúde preventiva',
  // 🛠️ SERVIÇOS GERAIS
  'eletricista', 'encanador', 'pedreiro', 'pintor', 'chaveiro', 'montagem de móveis', 'limpeza residencial', 'manutenção geral'
];

// ... (restante do arquivo constants.tsx) ...
// (O conteúdo restante do arquivo MOCK_CLASSIFIEDS, MOCK_REAL_ESTATE_PROPERTIES, etc., é omitido para brevidade, mas deve ser mantido)
export const EDITORIAL_SERVICES: EditorialCollection[] = [
  {
    id: 'culinaria-jpa',
    title: 'Melhores de JPA',
    subtitle: 'Onde comer bem no bairro',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop',
    keywords: ['comida', 'restaurante', 'lanches', 'pizza']
  },
  {
    id: 'servicos-confianca',
    title: 'Serviços de Confiança',
    subtitle: 'Profissionais avaliados por vizinhos',
    image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800&auto=format&fit=crop',
    keywords: ['serviços', 'reformas', 'consertos']
  }
];

export const quickFilters = [
  { id: 'top_rated', label: 'Top Avaliados', icon: 'star' },
  { id: 'open_now', label: 'Aberto Agora', icon: 'clock' },
  { id: 'nearby', label: 'Perto de Mim', icon: 'zap' },
  { id: 'cashback', label: 'Com Cashback', icon: 'percent' }
];

export const STORIES: Story[] = [
  { id: 's1', name: 'Hamburgueria', image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?q=80&w=400&auto=format&fit=crop' },
  { id: 's2', name: 'Salão Vip', image: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=400&auto=format&fit=crop' },
  { id: 's3', name: 'Pet Shop', image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=400&auto=format&fit=crop' },
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    role: 'Atendente de Balcão',
    company: 'Padaria Imperial',
    neighborhood: 'Freguesia',
    category: 'Alimentação',
    type: 'CLT',
    salary: 'R$ 1.450,00',
    description: 'Atendimento ao público, organização e limpeza do local.',
    requirements: ['Experiência anterior', 'Boa comunicação'],
    schedule: '6x1',
    contactWhatsapp: '5521999999999',
    postedAt: 'Há 2h',
    isSponsored: true,
    sponsoredUntil: '2025-12-31',
    candidacy_method: 'whatsapp',
    modality: 'Presencial',
  },
  {
    id: 'job-2',
    role: 'Vendedor Externo',
    company: 'JPA Telecom',
    neighborhood: 'Taquara',
    category: 'Vendas',
    type: 'PJ',
    salary: 'Comissão + Ajuda de Custo',
    description: 'Vendas de planos de internet e TV a cabo.',
    requirements: ['Carro próprio', 'Experiência com vendas'],
    schedule: 'Seg-Sex',
    contactWhatsapp: '5521988888888',
    postedAt: 'Há 1 dia',
    isUrgent: true,
    candidacy_method: 'whatsapp',
    modality: 'Presencial',
  }
];

export const MOCK_CLASSIFIEDS: Classified[] = []; // Omitido para brevidade
export const MOCK_REAL_ESTATE_PROPERTIES: RealEstateProperty[] = []; // Omitido para brevidade
export const SPECIALTIES: Record<string, string[]> = {}; // Omitido para brevidade
export const OFFICIAL_COMMUNITIES: NeighborhoodCommunity[] = []; // Omitido para brevidade
export const MOCK_USER_COMMUNITIES: NeighborhoodCommunity[] = []; // Omitido para brevidade
export const NEIGHBORHOOD_COMMUNITIES: NeighborhoodCommunity[] = []; // Omitido para brevidade
export const MOCK_COMMUNITY_POSTS: CommunityPost[] = []; // Omitido para brevidade
export const STORES: Store[] = []; // Omitido para brevidade
export const CATEGORY_TOP_BANNERS: Record<string, Record<string, { image: string; storeId: string }[]>> = {}; // Omitido para brevidade
