
import React from 'react';
import { 
  Utensils, ShoppingCart, Scissors, Heart, PawPrint, Wrench, 
  Dumbbell, CarFront, BookOpen, Monitor, Shirt, Map as MapIcon, 
  Store as StoreIcon, Pill, Zap,
  Beef, Pizza, Croissant, Soup, Cake, Sandwich, 
  Stethoscope, Package, Clock, Settings, Users,
  Apple, Building2, Leaf, PaintRoller, Hammer, Droplets, 
  Baby, Microscope, Sparkles, Smile, Beer, 
  Activity, Globe, PartyPopper, Globe2, Flame, Home as HomeIcon,
  PenTool, Key, Landmark, TicketPercent, Bike, Info, Search,
  User, Dog, Cat, Bird, Fish, Rabbit, Watch, Footprints, Sun, Recycle, Palette, UserCheck, Truck, Ship, ShieldCheck
} from 'lucide-react';
import { AdType, Category, Store, Story, EditorialCollection, Job, CommunityPost, NeighborhoodCommunity, Classified, RealEstateProperty } from '@/types';

// Oficialmente renomeado de TUCO para LOKA
export const LOKA_MASCOT_BASE64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==";

export const NEIGHBORHOODS = [
  'Freguesia',
  'Taquara',
  'Pechincha',
  'Anil',
  'Tanque',
  'Curicica',
  'Praça Seca',
  'Vila Valqueire',
  'Camorim',
  'Vargem Pequena',
  'Vargem Grande',
  'Recreio',
  'Barra da Tijuca'
];

export const CATEGORIES: Category[] = [
  { id: 'cat-servicos', name: 'Serviços', slug: 'servicos', icon: <Wrench />, color: 'bg-brand-blue' },
  { id: 'cat-alimentacao', name: 'Alimentação & Produtos', slug: 'alimentacao', icon: <Soup />, color: 'bg-brand-blue' },
  { id: 'cat-restaurantes', name: 'Restaurantes & Delivery', slug: 'restaurantes', icon: <Utensils />, color: 'bg-brand-blue' },
  { id: 'cat-alimentacao-estilos', name: 'Alimentação & Estilos', slug: 'alimentacao-estilos', icon: <Leaf />, color: 'bg-brand-blue' },
  { id: 'cat-mercados', name: 'Mercados', slug: 'mercados', icon: <ShoppingCart />, color: 'bg-brand-blue' },
  { id: 'cat-farmacias', name: 'Farmácias', slug: 'farmacias', icon: <Pill />, color: 'bg-brand-blue' },
  { id: 'cat-autos', name: 'Autos', slug: 'autos', icon: <CarFront />, color: 'bg-brand-blue' },
  { id: 'cat-moda', name: 'Moda', slug: 'moda', icon: <Shirt />, color: 'bg-brand-blue' },
  { id: 'cat-beleza', name: 'Beleza', slug: 'beleza', icon: <Scissors />, color: 'bg-brand-blue' },
  { id: 'cat-casa', name: 'Casa', slug: 'casa', icon: <HomeIcon />, color: 'bg-brand-blue' },
  { id: 'cat-informatica', name: 'Informática', slug: 'informatica', icon: <Monitor />, color: 'bg-brand-blue' },
  { id: 'cat-pets', name: 'Pets', slug: 'pets', icon: <PawPrint />, color: 'bg-brand-blue' },
  { id: 'cat-saude', name: 'Saúde', slug: 'saude', icon: <Heart />, color: 'bg-brand-blue' },
  { id: 'cat-educacao', name: 'Educação', slug: 'educacao', icon: <BookOpen />, color: 'bg-brand-blue' },
  { id: 'cat-esporte', name: 'Esporte', slug: 'esporte', icon: <Dumbbell />, color: 'bg-brand-blue' },
  { id: 'cat-bemestar', name: 'Bem-estar', slug: 'bemestar', icon: <Smile />, color: 'bg-brand-blue' },
  { id: 'cat-infantil', name: 'Infantil', slug: 'infantil', icon: <Baby />, color: 'bg-brand-blue' },
  { id: 'cat-servicospublicos', name: 'Serviços Públicos', slug: 'servicospublicos', icon: <Landmark />, color: 'bg-brand-blue' },
  { id: 'cat-eventos-lazer', name: 'Eventos & Lazer', slug: 'eventos-lazer', icon: <PartyPopper />, color: 'bg-brand-blue' },
  { id: 'cat-condominios', name: 'Condomínios', slug: 'condominios', icon: <Building2 />, color: 'bg-brand-blue' },
  { id: 'cat-ofertas', name: 'Ofertas', slug: 'ofertas', icon: <TicketPercent />, color: 'bg-brand-blue' },
];

export const ACONTECENDO_AGORA_DATA = [
  { id: 1, type: 'Trânsito', image: 'https://images.unsplash.com/photo-1545147422-b96338ea878c?q=80&w=400&auto=format&fit=crop', authorName: 'CET-Rio JPA', authorAvatar: 'https://i.pravatar.cc/150?u=cetrio', timestamp: '15 min', neighborhood: 'Freguesia', icon: MapIcon },
  { id: 2, type: 'Achados', image: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?q=80&w=400&auto=format&fit=crop', authorName: 'Segurança Center', authorAvatar: 'https://i.pravatar.cc/150?u=segcenter', timestamp: '1h', neighborhood: 'Tanque', icon: Search },
  { id: 3, type: 'Pets Perdidos', image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?q=80&w=400&auto=format&fit=crop', authorName: 'Amigos dos Pets', authorAvatar: 'https://i.pravatar.cc/150?u=amigospets', timestamp: '2h', neighborhood: 'Anil', icon: PawPrint },
  { id: 4, type: 'Utilidade', image: 'https://images.unsplash.com/photo-1584515933487-9d317552d894?q=80&w=400&auto=format&fit=crop', authorName: 'Posto Saúde JPA', authorAvatar: 'https://i.pravatar.cc/150?u=postojpa', timestamp: '3h', neighborhood: 'Taquara', icon: Info },
  { id: 5, type: 'Promoção', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400&auto=format&fit=crop', authorName: 'Pizzaria do Zé', authorAvatar: 'https://i.pravatar.cc/150?u=pizzazé', timestamp: '4h', neighborhood: 'Pechincha', icon: Flame },
];

export const SUBCATEGORIES: Record<string, { name: string; icon: React.ElementType }[]> = {
  'Saúde': [
    { name: 'Mulher', icon: Heart },
    { name: 'Homem', icon: User },
    { name: 'Pediatria', icon: Baby },
    { name: 'Geriatria', icon: Users },
    { name: 'Odontologia', icon: Smile },
    { name: 'Fisioterapia', icon: Activity },
    { name: 'Psicologia', icon: Heart },
    { name: 'Nutrição', icon: Apple },
  ],
  'Pets': [
    { name: 'Cães', icon: Dog },
    { name: 'Gatos', icon: Cat },
    { name: 'Aves', icon: Bird },
    { name: 'Peixes', icon: Fish },
    { name: 'Roedores', icon: Rabbit },
    { name: 'Banho & Tosa', icon: Scissors },
    { name: 'Veterinários', icon: Stethoscope },
    { name: 'Outros', icon: PawPrint },
  ],
  'Moda': [
    { name: 'Feminino', icon: User },
    { name: 'Masculino', icon: User },
    { name: 'Infantil', icon: Baby },
    { name: 'Acessórios', icon: Watch },
    { name: 'Calçados', icon: Footprints },
    { name: 'Praia', icon: Sun },
    { name: 'Íntima', icon: Heart },
    { name: 'Brechós', icon: Recycle },
  ],
  'Beleza': [
    { name: 'Mulher', icon: User },
    { name: 'Homem', icon: User },
    { name: 'Cabelo', icon: Scissors },
    { name: 'Unhas', icon: Palette },
    { name: 'Maquiagem', icon: Sparkles },
    { name: 'Depilação', icon: Droplets },
    { name: 'Estética', icon: Smile },
    { name: 'Barbeiros', icon: UserCheck },
  ],
  'Autos': [
    { name: 'Carros', icon: CarFront },
    { name: 'Motos', icon: Bike },
    { name: 'Bikes', icon: Bike },
    { name: 'Elétricos', icon: Zap },
    { name: 'Caminhões', icon: Truck },
    { name: 'Barcos', icon: Ship },
    { name: 'Oficinas', icon: Settings },
    { name: 'Peças', icon: Package },
  ],
  'Serviços': [
    { name: 'Elétrica', icon: Zap },
    { name: 'Hidráulica', icon: Droplets },
    { name: 'Chaveiro', icon: Key },
    { name: 'Marido de Aluguel', icon: Hammer },
    { name: 'Pintura', icon: PaintRoller },
    { name: 'Limpeza', icon: Sparkles },
    { name: 'Jardinagem', icon: Leaf },
    { name: 'Montagem de Móveis', icon: Settings },
  ],
  'Alimentação & Produtos': [
    { name: 'Marmitas', icon: Package },
    { name: 'Lanches', icon: Sandwich },
    { name: 'Doces', icon: Cake },
    { name: 'Salgados', icon: Croissant },
    { name: 'Comida Caseira', icon: Soup },
    { name: 'Bebidas', icon: Beer },
    { name: 'Produtos Naturais', icon: Apple },
    { name: 'Congelados', icon: Package },
  ],
  'Alimentação & Estilos': [
    { name: 'Vegano', icon: Leaf },
    { name: 'Vegetariano', icon: Leaf },
    { name: 'Sem Glúten', icon: Activity },
    { name: 'Sem Lactose', icon: Activity },
    { name: 'Orgânicos', icon: Apple },
    { name: 'Natural', icon: Leaf },
    { name: 'Funcional', icon: Activity },
    { name: 'Alimentação Saudável', icon: Heart },
  ],
  'Restaurantes & Delivery': [
    { name: 'Pizzarias', icon: Pizza },
    { name: 'Hamburguerias', icon: Beef },
    { name: 'Brasileira', icon: Utensils },
    { name: 'Japonesa', icon: Globe2 },
    { name: 'Italiana', icon: Pizza },
    { name: 'Árabe', icon: Globe },
    { name: 'Self-service', icon: Utensils },
    { name: 'Delivery', icon: Bike },
  ],
  'Mercados': [
    { name: 'Supermercados', icon: ShoppingCart },
    { name: 'Mercadinhos', icon: StoreIcon },
    { name: 'Hortifruti', icon: Apple },
    { name: 'Açougue', icon: Beef },
    { name: 'Peixaria', icon: Globe },
    { name: 'Conveniência', icon: Clock },
    { name: 'Bebidas', icon: Beer },
    { name: 'Importados', icon: Globe2 },
  ],
  'Farmácias': [
    { name: 'Drogaria', icon: Pill },
    { name: 'Manipulação', icon: Microscope },
    { name: 'Homeopatia', icon: Stethoscope },
    { name: 'Suplementos', icon: Activity },
    { name: 'Perfumaria', icon: Sparkles },
    { name: 'Infantil', icon: Baby },
    { name: 'Ortopedia', icon: Activity },
    { name: 'Veterinária', icon: PawPrint },
  ],
  'Casa': [
    { name: 'Papelaria', icon: PenTool },
    { name: 'Decoração', icon: Sparkles },
    { name: 'Móveis', icon: HomeIcon },
    { name: 'Iluminação', icon: Zap },
    { name: 'Cama & Banho', icon: Heart },
    { name: 'Utensílios', icon: Utensils },
    { name: 'Jardinagem', icon: Leaf },
    { name: 'Segurança', icon: ShieldCheck },
  ],
  'Informática': [
    { name: 'Assistência', icon: Settings },
    { name: 'Vendas', icon: ShoppingCart },
    { name: 'Redes', icon: Globe },
    { name: 'Games', icon: PartyPopper },
    { name: 'Acessórios', icon: Monitor },
    { name: 'Software', icon: PenTool },
    { name: 'Impressoras', icon: Package },
    { name: 'Cursos', icon: BookOpen },
  ],
  'Educação': [
    { name: 'Escolas', icon: Building2 },
    { name: 'Idiomas', icon: Globe },
    { name: 'Cursos Livres', icon: BookOpen },
    { name: 'Reforço', icon: PenTool },
    { name: 'Música', icon: PartyPopper },
    { name: 'Artes', icon: PaintRoller },
    { name: 'Esportes', icon: Dumbbell },
    { name: 'Infantil', icon: Baby },
  ],
  'Esporte': [
    { name: 'Academias', icon: Dumbbell },
    { name: 'Artes Marciais', icon: Activity },
    { name: 'Natação', icon: Droplets },
    { name: 'Futebol', icon: PartyPopper },
    { name: 'Tênis', icon: Activity },
    { name: 'Crossfit', icon: Flame },
    { name: 'Yoga', icon: Smile },
    { name: 'Dança', icon: PartyPopper },
  ],
  'Bem-estar': [
    { name: 'Massagem', icon: Smile },
    { name: 'Terapia', icon: Heart },
    { name: 'Yoga', icon: Activity },
    { name: 'Pilates', icon: Activity },
    { name: 'Meditação', icon: Smile },
    { name: 'Nutrição', icon: Apple },
    { name: 'Estética', icon: Sparkles },
    { name: 'Spa', icon: Droplets },
  ],
  'Infantil': [
    { name: 'Brinquedos', icon: PartyPopper },
    { name: 'Roupas', icon: Shirt },
    { name: 'Escolas', icon: Building2 },
    { name: 'Festas', icon: Cake },
    { name: 'Saúde', icon: Heart },
    { name: 'Esportes', icon: Dumbbell },
    { name: 'Cursos', icon: BookOpen },
    { name: 'Berçários', icon: Baby },
  ],
  'Serviços Públicos': [
    { name: 'Saúde', icon: Heart },
    { name: 'Segurança', icon: ShieldCheck },
    { name: 'Educação', icon: BookOpen },
    { name: 'Transporte', icon: CarFront },
    { name: 'Lazer', icon: Sun },
    { name: 'Administração', icon: Landmark },
    { name: 'Correios', icon: Package },
    { name: 'Justiça', icon: Landmark },
  ],
  'Eventos & Lazer': [
    { name: 'Festas', icon: PartyPopper },
    { name: 'Shows', icon: PartyPopper },
    { name: 'Teatro', icon: Users },
    { name: 'Cinema', icon: Monitor },
    { name: 'Parques', icon: Leaf },
    { name: 'Esportes', icon: Dumbbell },
    { name: 'Gastronomia', icon: Utensils },
    { name: 'Turismo', icon: Globe },
  ],
  'Condomínios': [
    { name: 'Administração', icon: Landmark },
    { name: 'Manutenção', icon: Wrench },
    { name: 'Segurança', icon: ShieldCheck },
    { name: 'Limpeza', icon: Sparkles },
    { name: 'Jardinagem', icon: Leaf },
    { name: 'Jurídico', icon: Landmark },
    { name: 'Contabilidade', icon: Landmark },
    { name: 'Sistemas', icon: Monitor },
  ],
  'Ofertas': [
    { name: 'Alimentação', icon: Utensils },
    { name: 'Moda', icon: Shirt },
    { name: 'Beleza', icon: Scissors },
    { name: 'Saúde', icon: Heart },
    { name: 'Serviços', icon: Wrench },
    { name: 'Eletrônicos', icon: Monitor },
    { name: 'Casa', icon: HomeIcon },
    { name: 'Pets', icon: PawPrint },
  ],
};

export const STORES: Store[] = [
  {
    id: 'atual-clube',
    name: 'Atual Clube',
    category: 'Serviços',
    subcategory: 'Proteção Veicular',
    rating: 5.0,
    reviewsCount: 850,
    distance: 'Freguesia',
    adType: AdType.PREMIUM,
    description: 'Proteção veicular e benefícios exclusivos para Jacarepaguá.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=800'
  },
  {
    id: 'store-1',
    name: 'Studio Bella',
    category: 'Beleza',
    subcategory: 'Salão de Beleza',
    rating: 4.8,
    reviewsCount: 120,
    distance: '0.5km',
    adType: AdType.PREMIUM,
    description: 'Especialistas em cabelos e unhas.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800'
  },
  {
    id: 'store-2',
    name: 'Farma Vida',
    category: 'Farmácias',
    subcategory: 'Drogaria',
    rating: 4.5,
    reviewsCount: 85,
    distance: '1.2km',
    adType: AdType.STANDARD,
    description: 'Medicamentos e perfumaria com desconto.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Taquara',
    logoUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?q=80&w=800'
  },
  {
    id: 'store-3',
    name: 'Pet Care JPA',
    category: 'Pets',
    subcategory: 'Pet Shop',
    rating: 4.9,
    reviewsCount: 210,
    distance: '2.0km',
    adType: AdType.PREMIUM,
    description: 'Banho, tosa e veterinário 24h.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Pechincha',
    logoUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=800'
  },
  {
    id: 'store-4',
    name: 'Auto Center Prime',
    category: 'Autos',
    subcategory: 'Mecânica',
    rating: 4.7,
    reviewsCount: 150,
    distance: '3.5km',
    adType: AdType.STANDARD,
    description: 'Serviços automotivos de confiança.',
    verified: true,
    isOpenNow: false,
    neighborhood: 'Anil',
    logoUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=800'
  },
  {
    id: 'store-5',
    name: 'Café Carioca',
    category: 'Alimentação & Produtos',
    subcategory: 'Cafeteria',
    rating: 4.6,
    reviewsCount: 95,
    distance: '0.8km',
    adType: AdType.PREMIUM,
    description: 'O melhor café da região.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=800'
  },
  {
    id: 'store-6',
    name: 'Tech Info',
    category: 'Informática',
    subcategory: 'Assistência Técnica',
    rating: 4.4,
    reviewsCount: 60,
    distance: '1.5km',
    adType: AdType.STANDARD,
    description: 'Conserto de computadores e celulares.',
    verified: false,
    isOpenNow: true,
    neighborhood: 'Taquara',
    logoUrl: 'https://images.unsplash.com/photo-1597872252721-2405b85561eb?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1597872252721-2405b85561eb?q=80&w=800'
  },
  {
    id: 'store-7',
    name: 'Casa & Design',
    category: 'Casa',
    subcategory: 'Decoração',
    rating: 4.8,
    reviewsCount: 180,
    distance: '2.2km',
    adType: AdType.PREMIUM,
    description: 'Móveis e decoração para o seu lar.',
    verified: true,
    isOpenNow: false,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?q=80&w=800'
  },
  {
    id: 'store-8',
    name: 'Odonto Smile',
    category: 'Saúde',
    subcategory: 'Dentista',
    rating: 4.9,
    reviewsCount: 250,
    distance: '1.0km',
    adType: AdType.PREMIUM,
    description: 'Sorria com confiança.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Pechincha',
    logoUrl: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?q=80&w=800'
  },
  {
    id: 'store-9',
    name: 'Fit Center',
    category: 'Esporte',
    subcategory: 'Academia',
    rating: 4.7,
    reviewsCount: 300,
    distance: '0.3km',
    adType: AdType.PREMIUM,
    description: 'Sua saúde em primeiro lugar.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=800'
  },
  {
    id: 'store-10',
    name: 'Doceria Doce Vida',
    category: 'Alimentação & Produtos',
    subcategory: 'Doces',
    rating: 4.9,
    reviewsCount: 110,
    distance: '1.8km',
    adType: AdType.STANDARD,
    description: 'Bolos e doces artesanais.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Taquara',
    logoUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800'
  },
  {
    id: 'store-11',
    name: 'Ótica Visão',
    category: 'Saúde',
    subcategory: 'Ótica',
    rating: 4.6,
    reviewsCount: 75,
    distance: '2.5km',
    adType: AdType.STANDARD,
    description: 'Óculos de grau e sol.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Anil',
    logoUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800'
  },
  {
    id: 'store-12',
    name: 'Barbearia Alfa',
    category: 'Beleza',
    subcategory: 'Barbearia',
    rating: 4.8,
    reviewsCount: 140,
    distance: '0.6km',
    adType: AdType.PREMIUM,
    description: 'Estilo e tradição.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?q=80&w=800'
  },
  {
    id: 'store-13',
    name: 'Clínica Bem Estar',
    category: 'Saúde',
    subcategory: 'Clínica Médica',
    rating: 4.7,
    reviewsCount: 90,
    distance: '1.3km',
    adType: AdType.PREMIUM,
    description: 'Cuidando de você e sua família.',
    verified: true,
    isOpenNow: false,
    neighborhood: 'Pechincha',
    logoUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800'
  },
  {
    id: 'store-14',
    name: 'Papelaria Central',
    category: 'Casa',
    subcategory: 'Papelaria',
    rating: 4.5,
    reviewsCount: 50,
    distance: '0.9km',
    adType: AdType.STANDARD,
    description: 'Material escolar e escritório.',
    verified: false,
    isOpenNow: true,
    neighborhood: 'Taquara',
    logoUrl: 'https://images.unsplash.com/photo-1531297461136-82af022f0b91?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1531297461136-82af022f0b91?q=80&w=800'
  },
  {
    id: 'store-15',
    name: 'Restaurante Sabor Local',
    category: 'Restaurantes & Delivery',
    subcategory: 'Brasileira',
    rating: 4.8,
    reviewsCount: 220,
    distance: '1.1km',
    adType: AdType.PREMIUM,
    description: 'Comida caseira de qualidade.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=800'
  },
  {
    id: 'store-16',
    name: 'Lava Jato Express',
    category: 'Autos',
    subcategory: 'Lava Jato',
    rating: 4.6,
    reviewsCount: 80,
    distance: '2.8km',
    adType: AdType.STANDARD,
    description: 'Seu carro limpo em minutos.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Anil',
    logoUrl: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?q=80&w=800'
  },
  {
    id: 'store-17',
    name: 'Escola Evoluir',
    category: 'Educação',
    subcategory: 'Escola',
    rating: 4.9,
    reviewsCount: 160,
    distance: '1.6km',
    adType: AdType.PREMIUM,
    description: 'Educação de excelência.',
    verified: true,
    isOpenNow: false,
    neighborhood: 'Freguesia',
    logoUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=800'
  },
  {
    id: 'store-18',
    name: 'Mercado Popular',
    category: 'Mercados',
    subcategory: 'Mercadinho',
    rating: 4.4,
    reviewsCount: 200,
    distance: '0.4km',
    adType: AdType.STANDARD,
    description: 'Preço baixo todo dia.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Taquara',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=800'
  },
  {
    id: 'store-19',
    name: 'Salão Charm',
    category: 'Beleza',
    subcategory: 'Cabelereiro',
    rating: 4.7,
    reviewsCount: 130,
    distance: '1.9km',
    adType: AdType.PREMIUM,
    description: 'Realce sua beleza.',
    verified: true,
    isOpenNow: true,
    neighborhood: 'Pechincha',
    logoUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800'
  },
  {
    id: 'store-20',
    name: 'Serviços RJ',
    category: 'Serviços',
    subcategory: 'Manutenção',
    rating: 4.5,
    reviewsCount: 40,
    distance: '3.0km',
    adType: AdType.STANDARD,
    description: 'Reparos residenciais e comerciais.',
    verified: false,
    isOpenNow: true,
    neighborhood: 'Anil',
    logoUrl: 'https://images.unsplash.com/photo-1581092921461-eab6245b0262?q=80&w=200',
    image: 'https://images.unsplash.com/photo-1581092921461-eab6245b0262?q=80&w=800'
  }
];

export const STORIES: Story[] = [
  { id: 's1', name: 'Padaria Imperial', image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=400' },
  { id: 's2', name: 'Pet Shop Amigo', image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?q=80&w=400' },
];

export const MOCK_CLASSIFIEDS: Classified[] = [
  {
    id: 'cl-1',
    title: 'Vendo iPhone 13 Pro',
    advertiser: 'Lucas Silva',
    category: 'Desapega JPA',
    neighborhood: 'Freguesia',
    description: 'Em perfeito estado, 128GB.',
    timestamp: 'Há 2h',
    contactWhatsapp: '21999999999',
    typeLabel: 'Venda',
    price: 'R$ 4.500',
    imageUrl: 'https://images.unsplash.com/photo-1632661674596-df8be070a5c5?q=80&w=400',
    acceptsTrade: true,
    tradeInterests: ['Notebook', 'Videogame']
  },
  {
    id: 'cl-ado-1',
    title: 'Adoção de Filhote',
    advertiser: 'Ana Maria',
    category: 'Adoção de pets',
    neighborhood: 'Taquara',
    description: 'Filhote de 2 meses, vacinado.',
    timestamp: 'Há 5h',
    contactWhatsapp: '21988888888',
    typeLabel: 'Adoção',
    imageUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=400'
  }
];

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    role: 'Atendente de Balcão',
    company: 'Padaria Imperial',
    neighborhood: 'Freguesia',
    category: 'Vagas',
    type: 'CLT',
    description: 'Atendimento ao público.',
    requirements: ['Ensino Médio completo'],
    postedAt: 'Há 1 dia',
    contactWhatsapp: '21977777777',
    isVerified: true
  }
];

export const NEIGHBORHOOD_COMMUNITIES: NeighborhoodCommunity[] = [
  { id: 'comm-1', name: 'Moradores da Freguesia', description: 'Grupo oficial de moradores', image: '', icon: <Users />, color: 'bg-blue-500', membersCount: '15.4k' },
];

// Corrected NEIGHBORHOODS_COMMUNITIES to NEIGHBORHOOD_COMMUNITIES
export const OFFICIAL_COMMUNITIES: NeighborhoodCommunity[] = NEIGHBORHOOD_COMMUNITIES;
export const MOCK_USER_COMMUNITIES: NeighborhoodCommunity[] = [];

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    userId: 'u1',
    userName: 'João Morador',
    userAvatar: 'https://i.pravatar.cc/100?u=u1',
    authorRole: 'resident',
    content: 'Alguém sabe se a feira da praça vai acontecer amanhã?',
    type: 'poll',
    communityId: 'comm-1',
    neighborhood: 'Freguesia',
    timestamp: 'Há 10 min',
    likes: 12,
    comments: 4,
    theme: 'utilidade',
    isActiveResident: true
  }
];

export const MOCK_REAL_ESTATE_PROPERTIES: RealEstateProperty[] = [
  {
    id: 're-1',
    type: 'Comercial',
    title: 'Sala Comercial Tirol',
    description: 'Excelente localização no coração da Freguesia.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800',
    neighborhood: 'Freguesia',
    price: 1500,
    transaction: 'aluguel',
    area: 40,
    postedAt: 'Há 2 dias',
    propertyTypeCom: 'Sala comercial',
    highCeiling: true,
    loadingAccess: true
  }
];

export const CATEGORY_TOP_BANNERS: Record<string, Record<string, { storeId: string; image: string }[]>> = {
  'alimentacao': {
    'Freguesia': [{ storeId: 'f-1', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800' }],
    'Jacarepaguá (todos)': [{ storeId: 'f-1', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800' }]
  },
  'restaurantes': {
    'Freguesia': [{ storeId: 'f-1', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800' }],
    'Jacarepaguá (todos)': [{ storeId: 'f-1', image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=800' }]
  }
};
